// Generated by Skyramp v1.3.27 on 2026-06-21 17:17:34.286504466 +0000 UTC m=+676.148909313
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output auto_capitalization_lifecycle.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/auto_capitalization_lifecycle_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(116000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/organizations/77facfb2-9a01-4144-92d1-6569bc8cae95/projects/secret-management/673ff779-0ce2-492a-95d4-ab5e0e7a9933/settings?selectedTab=tab-secret-general");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="auto-capitalization-switch"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.waitForSelector("text=Enforce Capitalization");
    await expect(page).toHaveURL(/settings.*selectedTab=tab-secret-general/);
    await page.getByTestId("auto-capitalization-switch").click();
    await expect(page.getByTestId("auto-capitalization-switch")).toBeChecked();
    expect(errors).toHaveLength(0);
});
