// Generated by Skyramp v1.3.27 on 2026-06-21 17:17:31.697394088 +0000 UTC m=+673.559798935
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output auto_capitalization_enable.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/auto_capitalization_enable_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(343000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(6000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.locator("#new-project-name").fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Settings" }).click();
    await page.getByRole("link", { name: "Secrets Management" }).first().click();
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="auto-capitalization-switch"]').waitFor({ state: 'visible', timeout: 10000 });
    const responsePromise1 = page.waitForResponse("**/api/v1/projects/**");
    await page.getByTestId("auto-capitalization-switch").click();
    const response1 = await responsePromise1;

    expect(response0.status()).toBe(200);
    expect(response1.status()).toBe(200);
    await expect(page.getByTestId("auto-capitalization-switch")).toBeChecked();
    expect(errors).toHaveLength(0);
});
