// Generated by Skyramp v1.3.37 on 2026-08-09 19:10:59.800201388 +0000 UTC m=+1140.914079114
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output auto_capitalization_toggle_disable.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/auto_capitalization_toggle_disable_trace.zip

// Import of required libraries
import { expect, test, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(428000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "TestProject Secrets Management Add to favorites No description 3 Environments" }).click();
    await page.getByRole("button", { name: "Settings" }).click();
    await page.getByRole("link", { name: "Secrets Management" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);

    // Assert switch starts checked (ON) before disabling
    await expect(page.getByTestId("auto-capitalization-switch")).toBeChecked();

    const responsePromise1 = page.waitForResponse("**/api/v1/projects/**");
    await page.getByTestId("auto-capitalization-switch").click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Assert the switch is now unchecked (optimistic disable — immediate state transition)
    await expect(page.getByTestId("auto-capitalization-switch")).not.toBeChecked();

    expect(pageErrors).toHaveLength(0);
});
