// Generated by Skyramp v1.3.27 on 2026-06-21 17:18:15.606946457 +0000 UTC m=+762.491669548
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_action_bar_unselect_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/bulk_action_bar_unselect_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(113000);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/organizations/b0fb75aa-0f31-4b7b-8491-82e1d897893d/projects/secret-management/79bd332f-0b14-43a2-8617-c87cfeb8007c/overview");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Project Overview");
    await page.locator("#checkbox-select-all-rows").click();
    await expect(page.locator("#checkbox-select-all-rows")).toBeChecked();
    await page.getByRole("button", { name: "Unselect All" }).click();
    await expect(page.locator("#checkbox-select-all-rows")).not.toBeChecked();

    expect(errors).toHaveLength(0);
});
