// Generated by Skyramp v1.3.37 on 2026-08-09 19:17:57.437327105 +0000 UTC m=+1147.202215822
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_delete_dialog_initial_state.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/bulk_delete_dialog_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(240000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "TestProject Secrets Management Add to favorites No description 3 Environments" }).first().click();

    const existingSecret = page.getByRole("row", { name: "DIALOG_TEST_SECRET" });
    if (!(await existingSecret.isVisible().catch(() => false))) {
        await page.getByText("Add a New Secret").click();
        await page.getByRole("textbox", { name: "Type your secret name" }).fill("DIALOG_TEST_SECRET");
        await page.getByRole("textbox", { name: "secret value" }).fill("dialog-test-value");
        await page.getByRole("button", { name: "Create Secret" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    await expect(page.getByRole("row", { name: "DIALOG_TEST_SECRET" })).toBeVisible();

    await page.locator("#checkbox-select-all-rows").click();
    await expect(page.getByText("Selected")).toContainText("1 Selected");
    await page.getByText("Delete").click();
    await expect(page.getByRole("heading", { name: "Do you want to delete the" })).toContainText("delete the selected secrets");
    await expect(page.getByRole("cell", { name: "DIALOG_TEST_SECRET" })).toBeVisible();
    await expect(page.getByTestId("bulk-rollup-header")).not.toBeVisible();
    await page.getByRole("button", { name: "Cancel" }).click();

    await expect(page.getByRole("row", { name: "DIALOG_TEST_SECRET" })).toBeVisible();
    await expect(page.getByText("Selected")).toContainText("1 Selected");

    expect(pageErrors).toHaveLength(0);
});
