// Generated by Skyramp v1.3.37 on 2026-08-09 19:06:40.39179032 +0000 UTC m=+918.850567227
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_action_bar_unselect_all_resets_count.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/bulk_action_bar_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1409000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    const existingProject = page.getByRole('link', { name: 'TestProject' });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.locator("#new-project-name").fill("TestProject");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    const existingSecret = page.getByRole('row', { name: 'TEST_SECRET' });
    if (await existingSecret.isVisible().catch(() => false)) {
        // Secret already exists, proceed
    } else {
        await page.getByText("Add a New Secret").click();
        await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_SECRET");
        await page.getByRole("textbox", { name: "secret value" }).fill("test-value-123");
        await page.getByRole("button", { name: "Create Secret" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(20000);
    }

    await page.getByRole("row", { name: "TEST_SECRET" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(120000);

    await expect(page.getByText("Selected")).toHaveText("0 Selected");
    await page.locator("#checkbox-select-all-rows").click();
    // Wait for network activities to finish
    await page.waitForTimeout(120000);

    await expect(page.getByText("Selected")).toHaveText("1 Selected");
    await page.getByRole("button", { name: "Unselect All" }).click();
    await expect(page.getByText("Selected")).toHaveText("0 Selected");

    expect(pageErrors).toHaveLength(0);
});
