// Generated by Skyramp v1.3.27 on 2026-06-23 00:20:05.928616002 +0000 UTC m=+749.658575761
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_delete_dialog_cancel_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/bulk_delete_dialog_cancel_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(232000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/3e045bfb-d219-4e04-a035-8603a102f7ab/projects/secret-management/1863b19d-e158-4e72-96a1-1e5e95727a19/overview");
    await page.waitForLoadState('networkidle');
    await page.locator('h1').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("SELECTION_TEST_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("selection-test-value");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await page.locator("#checkbox-select-all-rows").click();
    await expect(page.getByText("Selected")).toContainText("1 Selected");
    await page.getByText("Delete").click();
    await expect(page.getByRole("heading", { name: /delete the selected secrets/i })).toBeVisible();
    await expect(page.getByRole("cell", { name: "SELECTION_TEST_KEY" })).toBeVisible();
    await expect(page.getByRole("columnheader", { name: "Development" })).toBeVisible();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("heading", { name: /delete the selected secrets/i })).not.toBeVisible();
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("SELECTION_TEST_KEY");
    await expect(page.getByRole("row")).toHaveCount(2);
    expect(pageErrors).toHaveLength(0);
});
