// Generated by Skyramp v1.3.37 on 2026-08-09 19:19:37.022447425 +0000 UTC m=+1327.450504028
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output create_secret_form_inline_validation.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/create_secret_form_inline_validation_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(198000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.waitForTimeout(3000);

    await page.locator("main").getByRole("button", { name: "Secrets Management" }).click();
    await page.locator("main").getByRole("button", { name: "Test Secrets Project Secrets Management Add to favorites No description 3" }).click();
    await page.getByText("Add a New Secret").click();
    await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("FORM_VALIDATION_KEY");
    await expect(page.getByRole("textbox", { name: "Type your secret name" })).toHaveValue("FORM_VALIDATION_KEY");
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("button", { name: "Cancel" })).not.toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
