// Generated by Skyramp v1.3.27 on 2026-06-22 20:29:06.436985982 +0000 UTC m=+734.197411425
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output create_secret_valid_submission_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/create_secret_valid_submission_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(691000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(2250);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/e76292a5-0216-4de9-80db-734d9efa871e/projects/secret-management/0e09daed-44f0-4612-8c66-49bb15f29fdd/overview");
    await page.waitForLoadState('networkidle');
    await page.locator("text=Add Secret").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("MY_TEST_SECRET");
    await expect(page.getByRole("textbox", { name: "Type your secret name" })).toHaveValue("MY_TEST_SECRET");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("MY_TEST_SECRET");
    await expect(page.getByRole("row")).toHaveCount(2);
    expect(errors).toHaveLength(0);
});
