// Generated by Skyramp v1.3.27 on 2026-06-22 20:29:15.316877049 +0000 UTC m=+743.077302502
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output create_secret_with_value_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/create_secret_with_value_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(190000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/login");
    await page.waitForSelector("text=Log in to Infisical");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/e76292a5-0216-4de9-80db-734d9efa871e/projects/secret-management/0e09daed-44f0-4612-8c66-49bb15f29fdd/overview");
    await page.waitForLoadState('networkidle');
    await page.locator("text=Add Secret").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("DB_PASSWORD");
    await page.getByPlaceholder("Enter secret value...").fill("supersecret123");
    await expect(page.getByRole("textbox", { name: "Type your secret name" })).toHaveValue("DB_PASSWORD");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await expect(page.getByRole("row")).toHaveCount(3);
    await expect(page.getByRole("textbox", { name: "Secret name" }).first()).toHaveValue("DB_PASSWORD");
    expect(errors).toHaveLength(0);
});
