// Generated by Skyramp v1.3.27 on 2026-06-21 17:18:07.624567264 +0000 UTC m=+705.199807714
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output create_secret_form_cancel.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/create_secret_form_cancel_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(323000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/organizations/d8ae55dd-f02d-46dc-8c08-60f6eb4c6cfb/projects/secret-management/c20ad07a-2573-4463-b9f0-134d28ee9c2d/overview");
    await page.waitForLoadState('networkidle');
    await page.locator("text=Add Secret").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEMP_KEY");
    await page.keyboard.press("Control+a");
    await page.keyboard.press("Backspace");
    await expect(page.getByRole("textbox", { name: "Type your secret name" })).toHaveValue("");
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("heading", { name: "Create Secret" })).not.toBeVisible();
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("MY_TEST_SECRET");
    expect(errors).toHaveLength(0);
});
