// Generated by Skyramp v1.3.27 on 2026-06-21 17:13:58.267713392 +0000 UTC m=+455.842953842
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output create_secret_happy_path.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/create_secret_happy_path_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(573000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(15000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.waitForLoadState('networkidle');

    await page.goto("http://localhost:8080/organizations/d8ae55dd-f02d-46dc-8c08-60f6eb4c6cfb/projects/secret-management/c20ad07a-2573-4463-b9f0-134d28ee9c2d/overview");
    await page.waitForLoadState('networkidle');
    await page.locator("text=Add Secret").waitFor({ state: 'visible', timeout: 10000 });

    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("NEW_HAPPY_PATH_SECRET");
    await expect(page.getByRole("textbox", { name: "Type your secret name" })).toHaveValue("NEW_HAPPY_PATH_SECRET");
    await page.getByRole("textbox", { name: "secret value" }).fill("supersecretvalue123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("heading", { name: "Create Secret" })).not.toBeVisible();
    await expect(page.getByRole("textbox", { name: "Secret name" }).last()).toHaveValue("NEW_HAPPY_PATH_SECRET");
    expect(errors).toHaveLength(0);
});
