// Generated by Skyramp v1.3.27 on 2026-06-22 20:29:12.103414832 +0000 UTC m=+739.863840255
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output create_secret_cancel_flow_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/create_secret_cancel_flow_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(444000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:8080/organizations/e76292a5-0216-4de9-80db-734d9efa871e/projects/secret-management/0e09daed-44f0-4612-8c66-49bb15f29fdd/overview");
    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/e76292a5-0216-4de9-80db-734d9efa871e/projects/secret-management/0e09daed-44f0-4612-8c66-49bb15f29fdd/overview");
    await page.waitForLoadState('networkidle');
    await page.locator("text=Add Secret").waitFor({ state: 'visible', timeout: 10000 });
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEMP");
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("");
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_VALIDATION");
    await page.keyboard.press("Control+a");
    await page.keyboard.press("Backspace");
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("SECOND_SECRET");
    await expect(page.getByRole("textbox", { name: "Type your secret name" })).toHaveValue("SECOND_SECRET");
    await page.locator("#radix-:r6b:").getByRole("button", { name: "Cancel" }).click();
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("MY_TEST_SECRET");
    expect(errors).toHaveLength(0);
});
