// Generated by Skyramp v1.3.37 on 2026-08-09 19:23:25.570841487 +0000 UTC m=+1687.587125854
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output datagrid_search_match_cell_id_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/datagrid_search_match_cell_id_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(239000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForSelector("text=Continue with Email");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/7debac26-aae5-46c5-abd9-3b1c6c459557/projects/secret-management/dc18cf27-5833-4e3f-b7d1-58c0e16c9862/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.getByRole("heading", { name: "Secrets Management" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("heading", { name: "Secrets Management" })).toBeVisible();

    await page.getByRole("combobox", { name: "Search by secret, folder, tag" }).fill("DATABASE_URL");
    await expect(page.getByRole("combobox", { name: "Search by secret, folder, tag" })).toHaveValue("DATABASE_URL");
    await expect(page.getByRole("tab", { name: "Development" })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
