// Generated by Skyramp v1.3.27 on 2026-06-21 17:16:30.83074894 +0000 UTC m=+616.920949988
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pam_project_creation_navigation.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/pam_project_creation_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(654000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5250);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.locator("#new-project-name").fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/2762cf49-3e7c-4510-92ab-9b9c70080f34/projects/pam");
    await page.waitForSelector("text=PAM");
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.locator("#new-project-name").fill("TestPAMProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("heading", { name: "Resources" })).toBeVisible();
    await page.getByRole("button", { name: "Add Resource" }).click();
    await page.getByRole("button", { name: "Close" }).click();
    await expect(page.getByRole("button", { name: "Add Resource" })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
