// Generated by Skyramp v1.3.37 on 2026-08-09 19:02:30.910438545 +0000 UTC m=+751.832323734
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output project_templates_empty_list_render.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/project_templates_empty_list_render_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(233000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForSelector("text=Continue with Email");

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Settings" }).click();
    await page.getByRole("link", { name: "Project Templates" }).click();
    await expect(page.getByRole("link", { name: "Project Templates" })).toBeVisible();
    await page.getByRole("textbox", { name: "Search templates..." }).fill("test");
    await expect(page.getByRole("textbox", { name: "Search templates..." })).toHaveValue("test");
    expect(pageErrors).toHaveLength(0);
});
