// Generated by Skyramp v1.3.37 on 2026-08-09 19:01:41.69876211 +0000 UTC m=+594.516510084
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output project_type_page_favorite_error_add.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/project_type_page_favorites_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(890000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.waitForTimeout(1000);

    const addFavBtn = page.getByRole("button", { exact: true, name: "Add to favorites" });
    const removeFavBtn = page.getByRole("button", { exact: true, name: "Remove from favorites" });
    if (!await addFavBtn.isVisible().catch(() => false) && !await removeFavBtn.isVisible().catch(() => false)) {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.locator("#new-project-name").fill("Test Project");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(20000);
        await page.getByRole("button", { name: "Projects" }).click();
        await page.waitForTimeout(2000);
    }
    if (await removeFavBtn.isVisible().catch(() => false)) {
        const responsePromiseUnfav = page.waitForResponse("**/api/v1/user/me/**");
        await removeFavBtn.click();
        await responsePromiseUnfav;
        await page.waitForTimeout(1000);
    }

    await expect(addFavBtn).toBeVisible();

    const responsePromise1 = page.waitForResponse("**/api/v1/user/me/**");
    await page.getByRole("button", { exact: true, name: "Add to favorites" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);
    await expect(page.getByRole("button", { exact: true, name: "Remove from favorites" })).toBeVisible();

    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    const responsePromise2 = page.waitForResponse("**/api/v1/user/me/**");
    await page.getByRole("button", { exact: true, name: "Remove from favorites" }).click();
    const response2 = await responsePromise2;
    expect(response2.status()).toBe(200);
    await expect(page.getByRole("button", { exact: true, name: "Add to favorites" })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
