// Generated by Skyramp v1.3.37 on 2026-08-09 19:08:20.302435744 +0000 UTC m=+838.757868608
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_import_saving_state_indicator_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_import_add_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(926000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.waitForTimeout(2000);
    // Idempotent: navigate into existing project or create it
    const existingProject = page.getByRole("button", { name: /Test Project/ });
    if (await existingProject.isVisible().catch(() => false)) {
      await existingProject.click();
    } else {
      const addNewBtn = page.getByRole("button", { name: "Add New Project" });
      if (await addNewBtn.isVisible().catch(() => false)) {
        await addNewBtn.click();
      } else {
        await page.getByRole("button", { name: "Create Project" }).click();
      }
      await page.locator("#new-project-name").fill("Test Project");
      await page.getByRole("button", { name: "Create Project" }).click();
      // Wait for network activities to finish
      await page.waitForTimeout(20000);
    }

    await page.getByRole("group").filter({ has: page.getByRole("button", { name: "Add Secret" }) }).getByRole("button").last().click();
    await page.getByRole("menuitem", { name: "Add Secret Import" }).click();
    await page.locator("#react-select-2-input").click();
    await page.getByRole("option", { name: "Staging" }).click();
    await page.getByRole("button", { name: "Create Link" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("group").filter({ has: page.getByRole("button", { name: "Add Secret" }) }).getByRole("button").last().click();
    await page.getByRole("menuitem", { name: "Add Secret Import" }).click();
    await page.locator("#react-select-3-input").click();
    await page.getByRole("option", { name: "Production" }).click();
    await page.getByRole("button", { name: "Create Link" }).click();
    await page.getByRole("textbox").fill("/");
    await page.getByRole("button", { name: "Create Link" }).click();
    await page.keyboard.press("Tab");
    await page.getByRole("button", { name: "Create Link" }).click();
    await page.evaluate(() => document.querySelector('dialog input[type="text"]')?.value || 'no input found');
    await page.evaluate(() => { const inputs = document.querySelectorAll('dialog [role="textbox"], dialog input, dialog textarea'); return Array.from(inputs).map(i => ({tag: i.tagName, type: i.type, value: i.value, textContent: i.textContent})); });
    await page.evaluate(() => Array.from(document.querySelectorAll('input')).map(i => ({id: i.id, name: i.name, type: i.type, value: i.value, placeholder: i.placeholder})).slice(0, 20));
    await page.evaluate(() => {
  const input = document.querySelector('input[name="secretPath"]');
  if (!input) return 'not found';
  const nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
  nativeInputValueSetter.call(input, '/');
  input.dispatchEvent(new Event('input', { bubbles: true }));
  input.dispatchEvent(new Event('change', { bubbles: true }));
  return 'done: ' + input.value;
});
    await page.getByRole("button", { name: "Close" }).click();
    await page.getByRole("group").filter({ has: page.getByRole("button", { name: "Add Secret" }) }).getByRole("button").last().click();
    await page.getByRole("menuitem", { name: "Add Secret Import" }).click();
    await page.getByRole("button", { name: "Create Link" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("body").click({ position: {"x": 760, "y": 400} });
    await page.keyboard.press("Escape");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Verify the import row is visible — the data-saving attribute (added in this PR)
    // is set on this element during drag-drop reordering to indicate the saving state
    await expect(page.getByRole("cell", { name: "Staging /" }).first()).toContainText("Staging");
    await expect(page.getByRole("row", { name: "Staging /" }).first()).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
