// Generated by Skyramp v1.3.27 on 2026-06-23 00:27:43.392361529 +0000 UTC m=+1215.014224482
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_import_delete_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_import_delete_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(567000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/2ce6fba5-57cc-4b7f-a670-a5125626c819/projects/secret-management/4abeef05-9769-4330-b3d3-a8d79f89be24/overview");
    await page.waitForSelector("text=1 - 2 of 2");
    await page.getByRole("row", { name: "Staging /" }).hover();
    await page.locator("tr").nth(2).locator(".active\\\\:scale-\\\\[0\\\\.99\\\\]").click();
    await page.getByRole("button", { name: "Remove" }).click();
    await expect(page.getByText("- 1 of 1")).toContainText("1 - 1 of 1");
    await expect(page.getByRole("cell", { name: "Production /prod" })).toContainText("Production");
    await expect(errors).toHaveLength(0);
});
