// Generated by Skyramp v1.3.27 on 2026-06-21 17:20:05.582822015 +0000 UTC m=+790.279658833
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sort_bidirectional.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_sort_bidirectional_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(178000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/organizations/7f7cc8ce-3f41-4192-bc56-43bfc147086f/projects/secret-management/7b9f8983-6d5f-46eb-870c-84b2c6d4cce4/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="secret-sort-toggle"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.waitForSelector("text=Secrets Management");
    await page.getByTestId("secret-sort-toggle").click();
    await expect(page).toHaveURL(/orderDirection=desc/);
    await page.getByTestId("secret-sort-toggle").click();
    await expect(page).toHaveURL(/secrets\/dev(?!.*orderDirection=desc)/);
    await expect(page.getByTestId("secret-sort-toggle")).toContainText("Key");
    expect(errors).toHaveLength(0);
});
