// Generated by Skyramp v1.3.27 on 2026-06-22 23:19:59.643300913 +0000 UTC m=+714.422941286
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_dashboard_data_state_empty_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_dashboard_data_state_empty_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(107000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/organizations/f927b319-87c6-4234-877f-7f02389a0c41/projects/secret-management/eb78dcef-f6b4-41d7-bbb5-6c14ae37e237/secrets/staging");
    await page.waitForLoadState('networkidle');
    await page.getByRole('button', { name: 'Add Secret' }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.locator('#dashboard')).toHaveAttribute('data-state', 'empty');
    await expect(page.getByRole('tab', { name: 'Staging' })).toHaveText('Staging');
    await expect(page.getByRole('button', { name: 'Add a New Secret' })).toBeVisible();
    await expect(page).toHaveURL(/secrets\/staging/);
    expect(pageErrors).toHaveLength(0);
});
