// Generated by Skyramp v1.3.27 on 2026-06-21 18:08:50.326605154 +0000 UTC m=+1666.034146665
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_detail_sidebar_accordion.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/sidebar_accordion_metadata_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2796000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(4500);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.locator("#new-project-name").fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_SECRET");
    await page.getByRole("textbox", { name: "secret value" }).fill("test_value_123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(9827);

    await page.getByRole("row", { name: "TEST_SECRET" }).hover();
    await page.getByRole("row", { name: "TEST_SECRET" }).hover();
    await page.mouse.move(863, 411);
    // Wait for network activities to finish
    await page.waitForTimeout(1500);

    await page.locator("body").click({ position: {"x": 1205, "y": 411} });
    await page.locator(".absolute.z-20").click();
    await page.keyboard.press("Escape");
    await page.getByRole("row", { name: "TEST_SECRET" }).hover();
    await page.waitForTimeout(3000);
    await page.locator("button:nth-child(9)").click();
    await page.keyboard.press("Escape");
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.waitForTimeout(4000);
    await page.getByRole("combobox").click();
    await page.locator("#radix-:r4l:").getByRole("button", { name: "Metadata" }).click();

    await expect(page.locator("#radix-:r4l:").getByRole("button", { name: "Metadata" })).toHaveAttribute("aria-expanded", "true");
    await expect(page.getByRole("heading", { name: "Version History" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Access List" })).toBeVisible();
    await expect(pageErrors).toHaveLength(0);
});
