// Generated by Skyramp v1.3.37 on 2026-08-09 19:09:41.552733418 +0000 UTC m=+1065.749865741
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sort_toggle_url_update_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_sort_toggle_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(782000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));
    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    const existingProject = page.getByRole('link', { name: 'TestProject' });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.locator("#new-project-name").fill("TestProject");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    if (await page.getByText("TEST_KEY").first().isVisible().catch(() => false)) {
        // Secret already exists, skip creation
    } else {
        await page.getByText("Add a New Secret").click();
        await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_KEY");
        await page.getByRole("textbox", { name: "secret value" }).fill("test-value");
        await page.getByRole("button", { name: "Create Secret" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(20000);
    }

    await page.waitForLoadState('networkidle');
    await page.getByRole("columnheader", { name: "Name" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("columnheader", { name: "Name" }).click();
    await page.evaluate(() => window.location.href);
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByTestId("secret-sort-toggle").click();
    await expect(page).toHaveURL(/orderDirection=desc/);
    await expect(page.getByTestId("secret-sort-toggle")).toHaveText("Key");
    expect(pageErrors).toHaveLength(0);
});
