// Generated by Skyramp v1.3.27 on 2026-06-21 18:00:40.536081002 +0000 UTC m=+1174.196121898
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sync_navigation_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_sync_navigation_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1908000);

    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(6000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.goto("http://localhost:8080/organizations/cac70719-2512-4c3c-b813-d6801d9e3d49/projects/secret-management/25b099a9-67d7-4a00-9c37-f62a531a044d/integrations?selectedTab=secret-syncs");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await page.waitForSelector("text=Secret Syncs");
    await expect(page.getByRole("heading", { name: "Project Integrations" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Secret Syncs" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Add Sync" })).toBeVisible();
    await expect(page.getByText("This project has no syncs configured")).toHaveText("This project has no syncs configured");
    expect(errors).toHaveLength(0);
});
