// Generated by Skyramp v1.3.27 on 2026-06-22 22:11:46.079699961 +0000 UTC m=+1713.228224663
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_input_combobox_role.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_input_combobox_role_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(195000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/72939dcb-9c25-4b3d-8e8a-a60c4cae2fd8/projects/secret-management/8ddb9bcc-d08d-4d4a-b620-f8521e5f9cc9/overview");
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Secret name" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("REF_SECRET");
    await expect(page.getByRole("combobox", { name: "secret value" })).toBeVisible();
    await expect(page.getByRole("row")).toHaveCount(2);

    expect(pageErrors).toHaveLength(0);
});
