// Generated by Skyramp v1.3.37 on 2026-08-09 19:07:57.374706672 +0000 UTC m=+1086.509929211
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_approval_no_error_state_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_approval_no_error_state_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(120000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.waitForTimeout(3000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/6e237bf6-a69a-4fb6-9c6e-7b75eef54621/projects/secret-management/30fccb7b-c778-4d50-8d63-ef7c7d655a2e/approval?selectedTab=approval-requests");
    await page.waitForSelector("text=Approval Workflows");

    await expect(page.getByRole("heading", { name: "Approval Workflows" })).toBeVisible();
    await expect(page.getByText("No Open Change Requests")).toBeVisible();
    await expect(page.getByText("Failed to load change requests")).not.toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
