// Generated by Skyramp v1.3.27 on 2026-06-23 00:16:28.798658432 +0000 UTC m=+540.420521395
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_import_reorder_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_import_reorder_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(981000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(6750);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.waitForTimeout(3000);
    const createBtn = page.getByRole("button", { name: "Add New Project" }).or(page.getByRole("button", { name: "Create Project" }));
    await createBtn.first().click();
    await page.locator("#new-project-name").fill("TestImportProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await expect(page.getByRole("heading", { name: "Project Overview" })).toBeVisible();

    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.border.cursor-pointer.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-all.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.border-project\\\\/25").click();
    await page.getByRole("menuitem", { name: "Add Secret Import" }).click();
    await page.locator("#react-select-2-input").click();
    await page.getByRole("option", { name: "Staging" }).click();
    await page.getByRole("button", { name: "Create Link" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await expect(page.getByRole("cell", { name: "Staging /" })).toContainText("Staging");
    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.border.cursor-pointer.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-all.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.border-project\\\\/25").click();
    await page.getByRole("menuitem", { name: "Add Secret Import" }).click();
    await page.locator("#react-select-3-input").click();
    await page.getByRole("option", { name: "Production" }).click();
    await page.getByRole("button", { name: "Create Link" }).click();
    await page.getByRole("textbox").fill("/");
    await page.getByRole("button", { name: "Create Link" }).click();
    await page.getByRole("textbox").fill("/prod");
    await page.getByRole("button", { name: "Create Link" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("- 2 of 2")).toContainText("1 - 2 of 2");
    await expect(page.getByRole("cell", { name: "Staging /" })).toBeVisible();
    await expect(page.getByRole("cell", { name: "Production /prod" })).toBeVisible();
    await page.mouse.move(344, 451);
    await page.mouse.down();
    await page.mouse.move(344, 398, { steps: 20 });
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v2/secret-imports/**");
    await page.mouse.up();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    await page.waitForTimeout(2000);
    await expect(page.getByRole("cell", { name: "Production /prod" })).toContainText("Production");
    await expect(page.getByText("- 2 of 2")).toContainText("1 - 2 of 2");
    await expect(errors).toHaveLength(0);
});
