// Generated by Skyramp v1.3.37 on 2026-08-09 19:18:39.734620524 +0000 UTC m=+1333.477216315
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_dropzone_no_secrets_found.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_dropzone_no_secrets_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import path from 'path';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(207000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "TestProject Secrets Management Add to favorites No description 3 Environments" }).click();
    // File upload
    const fileChooserPromise0 = page.waitForEvent("filechooser");
    await page.getByRole("button", { name: "Choose File" }).click();
    const fileChooser0 = await fileChooserPromise0;
    await fileChooser0.setFiles(path.join(__dirname, 'fixtures', "no-secrets.env"));
    // Wait for additional time after file upload
    await page.waitForTimeout(1500);

    // File upload
    const fileChooserPromise1 = page.waitForEvent("filechooser");
    await page.getByRole("button", { name: "Choose File" }).click();
    const fileChooser1 = await fileChooserPromise1;
    await fileChooser1.setFiles(path.join(__dirname, 'fixtures', "no-secrets.env"));
    await expect(page.getByText("No secrets found in the provided data.")).toBeVisible({ timeout: 8000 });
    expect(pageErrors).toHaveLength(0);
});
