// Generated by Skyramp v1.3.37 on 2026-08-09 19:23:03.523191578 +0000 UTC m=+1612.775746376
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_detail_open_row_state_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret-item-detail-open-row-state_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(156000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    const existingTestProject = page.getByRole('button', { name: /TestProject Secrets Management/ });
    if (await existingTestProject.isVisible().catch(() => false)) {
        await existingTestProject.click();
    }
    await page.waitForLoadState('networkidle');
    await page.getByRole("textbox", { name: "Secret name" }).waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("TEST_SECRET");
    await expect(page.locator('[data-detail-open="true"]')).toHaveCount(0);
    expect(pageErrors).toHaveLength(0);
});
