// Generated by Skyramp v1.3.27 on 2026-06-22 23:19:56.737328515 +0000 UTC m=+711.516968908
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_dashboard_sort_url_sync_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_dashboard_sort_url_sync_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(766000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(10500);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.locator("#new-project-name").fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("MY_SECRET_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("my-secret-value");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(14386);

    const currentUrl = page.url();
    const devSecretsUrl = currentUrl.replace(/\/overview.*/, '/secrets/dev');
    await page.goto(devSecretsUrl);
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="secret-sort-toggle"]').waitFor({ state: 'visible', timeout: 10000 });

    await expect(page.getByTestId("secret-sort-toggle")).toContainText("Key");
    await page.getByTestId("secret-sort-toggle").click();
    await expect(page).toHaveURL(/orderDirection=desc/);
    await expect(page).toHaveURL(/orderBy=name/);
    expect(pageErrors).toHaveLength(0);
});
