// Generated by Skyramp v1.3.27 on 2026-06-21 18:08:05.630111978 +0000 UTC m=+1600.329067075
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secrets_projects_list_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secrets_projects_list_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(92000);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => { pageErrors.push(error.message); });

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.getByRole("button", { name: "Secrets Management" }).click();
    await expect(page.getByRole("button", { name: "Test Secrets Project Secrets" })).toContainText("Test Secrets Project");
    await expect(page).toHaveURL(/\/projects\/secret-management$/);
    await expect(page.getByRole("heading", { name: "Secrets Management" })).toHaveText("Secrets Management");
    expect(pageErrors).toHaveLength(0);
});
