// Generated by Skyramp v1.3.27 on 2026-06-21 17:20:54.217144322 +0000 UTC m=+880.307345370
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secrets_dashboard_navigation.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secrets_dashboard_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.getByRole("textbox", { name: "Enter your email..." }).fill("admin@test.com");
    await page.getByRole("textbox", { name: "Enter your password..." }).fill("Password123!");
    const loginResp = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await loginResp;
    expect(response0.status()).toBe(200);
    await page.waitForTimeout(2000);
    await page.goto("http://localhost:8080/organizations/2762cf49-3e7c-4510-92ab-9b9c70080f34/projects/secret-management/37da4304-14b1-4444-820f-3ea9dc2f23c0/overview");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Project Overview");
    await expect(page).toHaveURL(/\/secret-management\/.*\/overview/);
    await expect(page.getByRole("heading", { name: "Project Overview" })).toHaveText("Project Overview");
    await expect(page.getByRole("button", { name: "Add Secret" })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
