// Generated by Skyramp v1.3.27 on 2026-06-22 22:14:33.400129317 +0000 UTC m=+1880.548654039
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_input_ref_selection.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_input_ref_selection_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(182000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.waitForURL("**/organizations/**");
    await page.goto("http://localhost:8080/organizations/72939dcb-9c25-4b3d-8e8a-a60c4cae2fd8/projects/secret-management/8ddb9bcc-d08d-4d4a-b620-f8521e5f9cc9/overview");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Add Secret");
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "secret value" }).fill("${");
    await page.locator("button").click();
    await expect(page.getByRole("button", { name: "suggestion-item" })).toContainText("REF_SECRET");
    await expect(page.getByRole("button", { name: "suggestion-item" })).toHaveCount(1);

    expect(pageErrors).toHaveLength(0);
});
