// Generated by Skyramp v1.3.37 on 2026-08-09 19:19:41.60895013 +0000 UTC m=+1332.037006733
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_pending_row_attributes.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_item_pending_row_attributes_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(419000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Test Secrets Project Secrets Management Add to favorites No description 3" }).click();
    await page.locator("main").getByRole("button", { name: "Batch Edit Mode" }).first().click();
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("STAGED_SECRET_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("staged-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await page.evaluate(() => { const row = document.querySelector('[data-testid="secret-row-pending"]'); return { found: !!row, testId: row?.getAttribute('data-testid'), state: row?.getAttribute('data-state') }; });
    await page.evaluate(() => { const rows = document.querySelectorAll('tr'); const info = []; rows.forEach(r => { info.push({ testId: r.getAttribute('data-testid'), state: r.getAttribute('data-state'), classes: r.className.substring(0, 100), text: r.textContent?.substring(0, 60) }); }); return info; });
    await expect(page.getByText("pending change")).toContainText("1 pending change");
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("STAGED_SECRET_KEY");

    expect(pageErrors).toHaveLength(0);
});
