// Generated by Skyramp v1.3.27 on 2026-06-23 00:22:10.329888654 +0000 UTC m=+881.951751607
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_import_persistence_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_import_persistence_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(432000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/2ce6fba5-57cc-4b7f-a670-a5125626c819/projects/secret-management/4abeef05-9769-4330-b3d3-a8d79f89be24/overview");
    await page.waitForLoadState('networkidle');
    await page.locator("h1").waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByRole("heading", { name: "Project Overview" })).toBeVisible();
    await expect(page.getByText("- 2 of 2")).toContainText("1 - 2 of 2");
    await expect(page.getByRole("cell", { name: "Production /prod" })).toContainText("Production");
    await expect(page.getByRole("cell", { name: "Staging /" })).toContainText("Staging");
    await expect(errors).toHaveLength(0);
});
