// Generated by Skyramp v1.3.27 on 2026-06-21 18:12:53.491685838 +0000 UTC m=+1909.199227358
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_detail_sidebar_version_history.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/sidebar_version_history_access_list_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(217000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/2bb2de2d-020c-4473-a3d6-f5f4e05d3730/projects/secret-management/3f6b9c3a-fcd7-4b52-b4ab-b7e242d84055/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(3000);
    await page.locator("form[id='dashboard']").hover();
    await page.getByRole("button", { name: "more" }).click();

    await expect(page.getByRole("heading", { name: "Version History" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Access List" })).toBeVisible();

    await page.getByRole("button", { name: "Version History" }).click();

    await expect(page.getByRole("button", { name: "Version History" })).toHaveAttribute("aria-expanded", "true");
    await expect(page.getByText("v1")).toBeVisible();

    await page.getByRole("button", { name: "Access List" }).click();

    await expect(page.getByRole("button", { name: "Access List" })).toHaveAttribute("aria-expanded", "true");
    await expect(page.getByRole("button", { name: "Analyze Access" })).toBeVisible();
    await expect(pageErrors).toHaveLength(0);
});
