// Generated by Skyramp v1.3.37 on 2026-08-09 19:15:16.666381911 +0000 UTC m=+1453.928426198
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sync_trigger_cancel.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_sync_trigger_modal_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(238000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.waitForLoadState('networkidle');

    // Login if the login form is visible (fresh session)
    const loginForm = page.getByRole("textbox", { name: "Enter your email..." });
    if (await loginForm.isVisible().catch(() => false)) {
        await loginForm.fill("admin@test.com");
        await page.getByRole("textbox", { name: "Enter your password..." }).fill("Password123!");
        await page.getByRole("button", { name: "Continue with Email" }).click();
        await page.waitForLoadState('networkidle');
    }

    await page.getByRole("heading", { name: "Organization Overview" }).waitFor({ state: 'visible', timeout: 15000 });
    await page.goto("http://localhost:8080/organizations/77884cac-ccd7-4730-9c2f-f2b3b105e2f7/projects/secret-management/9ea0cf34-8694-4a3f-bd85-2b0fc1b7f691/integrations?selectedTab=secret-syncs");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Add Sync" }).waitFor({ state: 'visible', timeout: 15000 });

    // Open destination picker modal
    await page.getByRole("button", { name: "Add Sync" }).click();
    await expect(page.getByRole("heading", { name: "Choose a destination" })).toBeVisible();

    // Cancel / close the modal — assert it is dismissed and list page is still intact
    await page.getByRole("button", { name: "Close" }).click();
    await expect(page.getByRole("heading", { name: "Choose a destination" })).not.toBeVisible();
    await expect(page.getByRole("button", { name: "Add Sync" })).toBeVisible();

    // Second open-then-select confirms modal can still be reopened after cancel
    await page.getByRole("button", { name: "Add Sync" }).click();
    await expect(page.getByRole("heading", { name: "Choose a destination" })).toBeVisible();
    await page.getByRole("button", { name: "GitHub logo CI/CD GitHub" }).nth(0).click();
    await expect(page.getByRole("heading", { name: "Source Secrets" })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
