// Generated by Skyramp v1.3.27 on 2026-06-21 17:30:16.401709043 +0000 UTC m=+1507.105205731
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_detail_sidebar_open.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_detail_sidebar_open_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1631000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(7500);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Create Project" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.locator("#new-project-name").fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_SECRET_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("test-secret-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("row", { name: "TEST_SECRET_KEY" }).hover();
    await page.mouse.move(440, 411);
    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.cursor-pointer.whitespace-nowrap.text-sm.font-medium.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.text-foreground.hover\\\\:bg-foreground\\\\/10.border-transparent.data-\\\\[state\\\\=open\\\\]\\\\:bg-foreground\\\\/10.h-7.\\\\[\\\\&\\\\>svg\\\\]\\\\:size-4.rounded-sm.\\\\[\\\\&\\\\>svg\\\\]\\\\:stroke-\\\\[1\\\\.75\\\\].w-0").click();
    await page.locator("button:nth-child(9)").click();
    await page.keyboard.press("Escape");
    await page.mouse.move(440, 411);
    await page.locator("button:nth-child(8) > .inline-flex").click();
    await page.keyboard.press("Escape");
    await page.mouse.move(440, 411);
    await page.locator("#dashboard").getByRole('button', { name: 'more' }).waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("#dashboard").getByRole('button', { name: 'more' }).click();
    await expect(page.getByText("Secret – TEST_SECRET_KEY")).toContainText("TEST_SECRET_KEY");
    await expect(page.getByRole("dialog")).toContainText("Value");
    await expect(page.getByRole("dialog")).toContainText("Secret – TEST_SECRET_KEY");
    await expect(page.getByRole("button", { name: "Share" })).toBeVisible();
    await expect(page.getByRole("dialog")).toContainText("Version History");
    expect(errors).toHaveLength(0);
});
