// Generated by Skyramp v1.3.27 on 2026-06-21 17:21:29.72329636 +0000 UTC m=+956.990478059
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_approval_filtered_empty_state.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_approval_filtered_empty_state_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(156000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);
    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8080/login");
    await page.waitForSelector("text=Continue with Email");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/b367d21a-74aa-4e5f-bf2c-d7eb2bfce18b/projects/secret-management/7e60416c-1707-4936-98d2-e37611e944d6/approval");
    await page.waitForLoadState('networkidle');
    await page.locator("text=No Open Change Requests").waitFor({ state: 'visible', timeout: 30000 });
    await page.getByRole("textbox", { name: "Search change requests by" }).fill("nonexistent-filter-term");
    await page.waitForTimeout(2000);
    await expect(page.getByRole("textbox", { name: "Search change requests by" })).toHaveValue("nonexistent-filter-term");
    await expect(page.getByText("No Requests Match Filters")).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
