// Generated by Skyramp v1.3.27 on 2026-06-23 00:33:11.317159445 +0000 UTC m=+1492.445368679
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_list_inline_edit_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_list_inline_edit_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1326000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.waitForSelector("text=Log in to Infisical");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/fb4a64b3-fb23-47f2-93fe-e74882f013bf/projects/secret-management/f8a559be-3b26-41ef-b184-cf94aca998ba/overview");
    await page.waitForLoadState('networkidle');

    await page.waitForSelector("text=Add a New Secret");
    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("DETAIL_OPEN_TEST_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("initial-secret-value");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("row", { name: "DETAIL_OPEN_TEST_KEY" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("body").click({ position: {"x": 800, "y": 411} });
    await page.keyboard.press("Escape");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("body").click({ position: {"x": 935, "y": 411} });

    const playwrightRequest0: Record<string, any> = {"secretValue": "updated-via-inline"};

    await page.getByRole("textbox", { name: "secret value" }).fill(getValue(playwrightRequest0, "secretValue"));
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v4/secrets/**");
    await page.locator("body").click({ position: {"x": 1158, "y": 410} });
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.waitForSelector("text=updated-via-inline");
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("DETAIL_OPEN_TEST_KEY");
    await expect(page.getByRole("row", { name: "DETAIL_OPEN_TEST_KEY" })).toHaveCount(1);
    expect(pageErrors).toHaveLength(0);
});
