// Generated by Skyramp v1.3.27 on 2026-06-23 00:33:15.271445023 +0000 UTC m=+1496.399654237
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_list_reveal_values_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_list_reveal_values_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(709000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/organizations/fb4a64b3-fb23-47f2-93fe-e74882f013bf/projects/secret-management/f8a559be-3b26-41ef-b184-cf94aca998ba/overview");
    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/fb4a64b3-fb23-47f2-93fe-e74882f013bf/projects/secret-management/f8a559be-3b26-41ef-b184-cf94aca998ba/overview");
    await page.waitForLoadState('networkidle');
    await page.locator('[role="textbox"][aria-label="Secret name"]').first().waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("row", { name: "DETAIL_OPEN_TEST_KEY" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("body").click({ position: {"x": 921, "y": 411} });
    await page.waitForTimeout(2000);
    await page.keyboard.press("Escape");
    await page.keyboard.press("Escape");
    await page.locator("main").getByRole("button", { name: "Reveal Values" }).click();
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("DETAIL_OPEN_TEST_KEY");
    await expect(page.locator("main").getByRole("button", { name: "Hide Values" })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
