// Generated by Skyramp v1.3.27 on 2026-06-21 17:30:17.990449371 +0000 UTC m=+1508.693946038
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_detail_sidebar_comment.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_detail_sidebar_comment_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(276000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8080/organizations/715b57b9-6396-4af8-bb5d-1abb432a4f1b/projects/secret-management/20531c48-88e0-48d3-b77e-d6db658bb38c/secrets/dev");
    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.waitForLoadState('networkidle');
    await page.goto("http://localhost:8080/organizations/715b57b9-6396-4af8-bb5d-1abb432a4f1b/projects/secret-management/20531c48-88e0-48d3-b77e-d6db658bb38c/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.locator("#dashboard").getByRole('button', { name: 'more' }).waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("#dashboard").getByRole('button', { name: 'more' }).click();
    await page.getByRole("textbox", { name: "add a comment or note to this" }).fill("test comment for sidebar");
    await expect(page.getByRole("textbox", { name: "add a comment or note to this" })).toHaveValue("test comment for sidebar");
    await page.getByRole("button", { name: "Close" }).click();
    await expect(page.getByRole("dialog")).not.toBeVisible();
    await expect(page.getByText("pending change")).toContainText("1 pending change");
    await expect(page.getByRole("button", { name: "Save Changes" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
