// Generated by Skyramp v1.3.27 on 2026-06-22 22:08:49.296923754 +0000 UTC m=+1536.445448486
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_input_aria_expanded.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_input_aria_expanded_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(353000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "secret value" }).fill("${");

    // After typing "${", the autocomplete popup should open with exactly 3 environment choices
    await expect(page.getByRole("button", { name: "suggestion-item" })).toHaveCount(3);

    expect(pageErrors).toHaveLength(0);
});
