// Generated by Skyramp v1.3.37 on 2026-08-09 19:07:03.141771995 +0000 UTC m=+585.491751917
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_settings_tab_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_settings_tab_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(234000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.waitForTimeout(2000);

    const existingProject = page.getByText('test-project').first();
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Create Project" }).click();
        await page.locator("#new-project-name").fill("test-project");
        await page.getByRole("button", { name: "Create Project" }).click();
    }

    await page.getByRole("button", { name: "Settings" }).click();
    await page.getByRole("link", { name: "Secrets Management" }).click();

    await expect(page).toHaveURL(/tab-secret-general/);
    await expect(page.getByRole("heading", { name: "Project Settings" })).toHaveText("Project Settings");

    expect(pageErrors).toHaveLength(0);
});
