// Generated by Skyramp v1.3.27 on 2026-06-23 00:33:19.438507573 +0000 UTC m=+1500.566716797
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_list_add_secret_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_list_add_second_secret_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(187000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.waitForSelector("text=Log in to Infisical");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/fb4a64b3-fb23-47f2-93fe-e74882f013bf/projects/secret-management/f8a559be-3b26-41ef-b184-cf94aca998ba/overview");
    await page.waitForLoadState('networkidle');
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("NEW_UNIQUE_SECRET");
    await page.getByPlaceholder("Enter secret value...").fill("unique-secret-value");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await page.waitForSelector("text=NEW_UNIQUE_SECRET");
    await expect(page.getByRole("textbox", { name: "Secret name" }).last()).toHaveValue("NEW_UNIQUE_SECRET");
    expect(pageErrors).toHaveLength(0);
});
