// Generated by Skyramp v1.3.37 on 2026-08-09 19:09:52.118853881 +0000 UTC m=+1076.315986254
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sort_url_persistence_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_sort_url_persistence_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(78000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));
    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.waitForSelector("text=Secrets Management");
    await expect(page).toHaveURL(/orderDirection=desc/);
    await expect(page.getByTestId("secret-sort-toggle")).toHaveText("Key");
    expect(pageErrors).toHaveLength(0);
});
