// Generated by Skyramp v1.3.37 on 2026-08-09 19:17:36.979227048 +0000 UTC m=+1286.231781846
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_detail_edit_list_update_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret-detail-edit-list-immediate-update_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2220000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.locator("main").getByRole("tab", { name: "All Projects" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const existingProject = page.getByRole('link', { name: 'TestProject' });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.locator("#new-project-name").fill("TestProject");
        await page.getByRole("button", { name: "Create Project" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(3000);
    }

    const existingSecret = page.getByRole("row", { name: "TEST_SECRET" });
    if (!(await existingSecret.isVisible().catch(() => false))) {
        await page.getByText("Add a New Secret").click();
        await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_SECRET");
        await page.getByRole("textbox", { name: "secret value" }).fill("initial_value");
        await page.getByRole("button", { name: "Create Secret" }).click();
        // Wait for network activities to finish
        await page.waitForTimeout(20000);
    }

    await page.evaluate(() => { const el = document.querySelector('[data-testid="secret-row-value-cell"]'); if (el) { el.click(); return 'clicked'; } return 'not found'; });
    // Wait for network activities to finish
    await page.waitForTimeout(78643);

    await page.getByRole("row", { name: "TEST_SECRET" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("body").click({ position: {"x": 865, "y": 411} });
    await page.keyboard.press("Escape");
    await page.getByRole("textbox", { name: "secret value" }).fill("updated_value");
    await page.keyboard.press("Enter");
    await page.waitForTimeout(3000);
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v4/secrets/**");
    await page.locator('[class*="border-success"]').first().click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await expect(page.getByRole("textbox", { name: "secret value" })).toHaveValue("updated_value");
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("TEST_SECRET");
    expect(pageErrors).toHaveLength(0);
});
