// Generated by Skyramp v1.3.37 on 2026-08-09 19:11:17.617642767 +0000 UTC m=+1183.591479868
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_detail_sidebar_render.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_detail_sidebar_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1632000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    const existingProject = page.getByRole("link", { name: "TestProject" });
    if (await existingProject.isVisible().catch(() => false)) {
      await existingProject.click();
    } else {
      await page.getByRole("button", { name: "Add New Project" }).click();
      await page.locator("#new-project-name").fill("TestProject");
      await page.getByRole("button", { name: "Create Project" }).click();
    }
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_SECRET");
    await page.getByRole("textbox", { name: "secret value" }).fill("my-secret-value");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(9682);

    await page.getByRole("row", { name: "TEST_SECRET" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(120000);

    await page.evaluate(() => {
  // Find the button that opens the secret detail sidebar (usually the last icon button in the row)
  const rows = document.querySelectorAll('tbody tr');
  if (rows.length > 0) {
    const buttons = rows[0].querySelectorAll('button');
    // The explore/detail button is typically the last one
    if (buttons.length > 0) {
      const lastBtn = buttons[buttons.length - 1];
      const rect = lastBtn.getBoundingClientRect();
      return { x: rect.x, y: rect.y, width: rect.width, height: rect.height, count: buttons.length, title: lastBtn.title || lastBtn.getAttribute('aria-label') || 'no-label' };
    }
  }
  return { error: 'no rows' };
});
    await page.evaluate(() => {
  const rows = document.querySelectorAll('tbody tr');
  if (rows.length > 0) {
    const buttons = rows[0].querySelectorAll('button');
    return Array.from(buttons).map((btn, i) => {
      const rect = btn.getBoundingClientRect();
      return { i, x: rect.x, y: rect.y, w: rect.width, h: rect.height, title: btn.title, label: btn.getAttribute('aria-label'), text: btn.textContent.substring(0,30) };
    });
  }
  return [];
});
    await page.mouse.move(640, 411);
    await page.evaluate(() => {
  const rows = document.querySelectorAll('tbody tr');
  if (rows.length > 0) {
    const buttons = rows[0].querySelectorAll('button');
    return Array.from(buttons).map((btn, i) => {
      const rect = btn.getBoundingClientRect();
      const style = window.getComputedStyle(btn);
      return { i, x: Math.round(rect.x), y: Math.round(rect.y), w: Math.round(rect.width), h: Math.round(rect.height), vis: style.visibility, opacity: style.opacity };
    }).filter(b => b.w > 0);
  }
  return [];
});
    await page.locator("button:nth-child(9)").click();
    await page.keyboard.press("Escape");
    await page.mouse.move(640, 411);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("body").click({ position: {"x": 930, "y": 411} });
    await page.mouse.move(640, 411);
    // Wait for network activities to finish
    await page.waitForTimeout(103125);

    await page.mouse.move(640, 411);
    // Wait for network activities to finish
    await page.waitForTimeout(1500);

    await page.locator("body").click({ position: {"x": 1145, "y": 411} });
    await page.evaluate(() => {
  // The button that opens the detail sidebar has ariaLabel="more"
  const buttons = document.querySelectorAll('button[aria-label="more"]');
  return Array.from(buttons).map((btn, i) => {
    const rect = btn.getBoundingClientRect();
    const disabled = btn.disabled;
    return { i, x: Math.round(rect.x), y: Math.round(rect.y), w: Math.round(rect.width), h: Math.round(rect.height), disabled, title: btn.title };
  });
});
    await page.mouse.move(640, 411);
    await page.keyboard.press("Escape");
    await page.keyboard.press("Escape");
    await page.locator("div").nth(0).click();
    await expect(page.getByRole("dialog")).toContainText("Value");
    await expect(page.getByRole("dialog")).toContainText("Secret");
    await expect(page.getByRole("dialog")).toContainText("Comments & Notes");
    await expect(page.getByRole("dialog")).toContainText("Version History");
});
