// Generated by Skyramp v1.3.27 on 2026-06-23 00:20:09.528500267 +0000 UTC m=+753.258460026
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output selection_panel_unselect_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/selection_panel_unselect_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(187000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/3e045bfb-d219-4e04-a035-8603a102f7ab/projects/secret-management/1863b19d-e158-4e72-96a1-1e5e95727a19/overview");
    await page.waitForLoadState('networkidle');
    await page.locator('h1').waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("#checkbox-select-all-rows").click();
    await expect(page.getByText("Selected")).toContainText("1 Selected");
    await page.getByRole("button", { name: "Unselect All" }).click();
    await expect(page.getByText("0 Selected")).toBeVisible();
    await expect(page.getByRole("button", { name: "Add Tags" })).not.toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
