// Generated by Skyramp v1.3.27 on 2026-06-21 17:21:28.226904181 +0000 UTC m=+705.741861690
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output settings_no_legacy_section.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/settings_no_legacy_section_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(624000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8080/login");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(9000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.locator('button:has-text("Create Project"), button:has-text("Add New Project")').first().waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.locator("#new-project-name").fill("Test Project");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Settings" }).click();
    await page.getByRole("link", { name: "Secrets Management" }).click();

    await expect(page).toHaveURL(/selectedTab=tab-secret-general/);
    await expect(page.getByRole("heading", { name: "Project Settings" })).toHaveText("Project Settings");
    await expect(page.getByText("Allow Secret Sharing")).toBeVisible();
    await expect(page.getByText("Version Retention")).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
