// Generated by Skyramp v1.3.27 on 2026-06-21 17:16:45.885608321 +0000 UTC m=+502.399556985
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sidebar_breakpoint_desktop.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/sidebar_breakpoint_desktop_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(363000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5250);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.goto("http://localhost:8080");
    await expect(page).toHaveURL(/\/organizations\//);
    await expect(page.locator('[data-slot="sidebar-wrapper"]')).toHaveAttribute('data-breakpoint', 'desktop');
    await expect(page.getByRole("button", { name: "Toggle Sidebar" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
