// Generated by Skyramp v1.3.27 on 2026-06-21 17:16:48.555376397 +0000 UTC m=+505.069325051
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output sidebar_access_control_navigation.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/sidebar_access_control_navigation_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(74000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.getByRole("link", { name: "Access Control" }).click();
    await expect(page).toHaveURL(/\/access-management/);
    await expect(page.getByRole("heading", { name: "Organization Access Control" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
