// Generated by Skyramp v1.3.27 on 2026-06-21 17:24:29.563161179 +0000 UTC m=+1064.401348093
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ssh_host_filter_no_match_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/ssh_host_filter_no_match_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(123000);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.waitForLoadState('networkidle');
    await page.locator('#email').fill('admin@test.com');
    await page.locator('#current-password').fill('Password123!');
    await page.getByRole('button', { name: 'Continue with Email' }).click();
    await page.waitForURL('**/organizations/**', { timeout: 15000 });

    await page.goto("http://localhost:8080/organizations/04448368-9df9-49c8-ac68-15ef10910304/projects/ssh/ad1aef09-15ef-4ffb-86cb-f44d13365470/overview");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="ssh-host-filter"]').waitFor({ state: 'visible', timeout: 15000 });

    await page.getByTestId("ssh-host-filter").fill("zzz");
    await expect(page.getByTestId("ssh-host-filter")).toHaveValue("zzz");
    await expect(page.getByText("No hosts match your search")).toBeVisible();
    await expect(page.getByRole("row")).toHaveCount(2);

    expect(errors).toHaveLength(0);
});
