// Generated by Skyramp v1.3.37 on 2026-08-09 19:04:53.118337462 +0000 UTC m=+881.136104577
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ssh_host_filter_no_match_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/ssh_host_filter_no_match_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(189000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Navigate directly to the SSH hosts page
    await page.waitForTimeout(2000);
    await page.goto("http://localhost:8080/organizations/bdf1a55a-f940-4ebf-9254-ce4c461538e2/projects/ssh/dd543082-29c1-438f-a5dd-08edcf66a183/overview");
    await page.waitForLoadState('networkidle');
    await page.getByTestId("ssh-host-filter").waitFor({ state: 'visible', timeout: 15000 });

    await page.getByTestId("ssh-host-filter").fill("xyzzzz");
    await page.getByTestId("ssh-host-filter-no-match").waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByTestId("ssh-host-filter")).toHaveValue("xyzzzz");
    await expect(page.getByTestId("ssh-host-filter-no-match")).toContainText("No hosts match your search");
    await expect(page.getByRole("row").filter({ hasText: "web-server" })).toHaveCount(0);
    await expect(page.getByRole("row").filter({ hasText: "db-primary" })).toHaveCount(0);

    expect(pageErrors).toHaveLength(0);
});
