// Generated by Skyramp v1.3.27 on 2026-06-21 17:24:28.078317059 +0000 UTC m=+1062.916503993
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ssh_host_filter_hostname_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/ssh_host_filter_hostname_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1255000);

    const errors: Error[] = [];
    page.on('pageerror', err => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/04448368-9df9-49c8-ac68-15ef10910304/projects/ssh/ad1aef09-15ef-4ffb-86cb-f44d13365470/overview");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="ssh-host-filter"]').waitFor({ state: 'visible', timeout: 15000 });

    await page.getByTestId("ssh-host-filter").fill("web");
    await expect(page.getByTestId("ssh-host-filter")).toHaveValue("web");
    await expect(page.getByRole("row")).toHaveCount(3);
    await expect(page.getByRole("cell", { name: "web-server.example.com" })).toHaveText("web-server.example.com");

    expect(errors).toHaveLength(0);
});
