// Generated by Skyramp v1.3.27 on 2026-06-21 17:19:11.052111944 +0000 UTC m=+836.007211321
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/project_template_environments_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1398000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:8080/login");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);
    await expect(page).toHaveURL(/organizations/);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/07be2c75-04f0-4eb7-b972-cbb33d119778/settings?selectedTab=project-templates");
    await page.waitForLoadState('networkidle');
    await page.locator("text=No project templates found").waitFor({ state: 'visible', timeout: 15000 });
    await page.waitForSelector("text=No project templates found");
    await expect(page.getByRole("row")).toHaveCount(2);
    await page.getByRole("textbox", { name: "Search templates..." }).fill("test-template");
    await expect(page.getByText("No project templates match")).toContainText("No project templates match search");
    await expect(page.getByRole("textbox", { name: "Search templates..." })).toHaveValue("test-template");
    expect(errors).toHaveLength(0);
});
