// Generated by Skyramp v1.3.27 on 2026-06-21 18:02:12.552434499 +0000 UTC m=+1247.251389595
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secrets_index_redirect_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2178000);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => { pageErrors.push(error.message); });

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: /Add New Project|Create Project/ }).click();
    await page.locator("#new-project-name").fill("Test Secrets Project");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.waitForTimeout(2000);
    await page.waitForTimeout(3000);
    await page.waitForTimeout(3000);
    await expect(page.getByRole("combobox")).toContainText("Development");
    await expect(page.getByRole("heading", { name: "Project Overview" })).toHaveText("Project Overview");
    await expect(page).toHaveURL(/\/overview$/);

    // Test the core PR behavior: /secrets index redirects to /secrets/$envSlug
    const projectUrl = page.url();
    const secretsUrl = projectUrl.replace('/overview', '/secrets');
    await page.goto(secretsUrl);
    await expect(page).toHaveURL(/\/secrets\/[a-z]+$/);

    expect(pageErrors).toHaveLength(0);
});
