// Generated by Skyramp v1.3.27 on 2026-06-21 17:21:31.32104476 +0000 UTC m=+708.836002250
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output version_retention_update.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/version_retention_update_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(66000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    await page.goto("http://localhost:8080/organizations/36d7b9af-d104-4bdd-bc1e-e5b57f234855/projects/secret-management/6232275a-5471-4ae1-b957-f9b197307194/settings?selectedTab=tab-secret-general");
    await page.waitForLoadState('networkidle');
    await page.locator("#pitVersionLimit").waitFor({ state: 'visible', timeout: 10000 });
    await page.waitForSelector("text=Version Retention");
    await expect(page.getByRole("heading", { name: "Project Settings" })).toHaveText("Project Settings");
    await page.locator("#pitVersionLimit").fill("20");
    await expect(page.getByRole("spinbutton", { name: "Recent versions to keep" })).toHaveValue("20");
    expect(pageErrors).toHaveLength(0);
});
