// Generated by Skyramp v1.3.27 on 2026-06-20 22:05:00.672283174 +0000 UTC m=+304.336237847
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output project-favorites-toast.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/e2e/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/project_favorites_toast_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(283000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:8080/login");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(3750);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator('#email').waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(15000);

    await page.waitForSelector("text=Test Favorites Project");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/user/me/**");
    await page.getByRole("button", { exact: true, name: "Add to favorites" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);
    await expect(page.getByRole("button", { exact: true, name: "Remove from favorites" })).toBeVisible();
    await expect(page.getByText("Project added to favorites")).toBeVisible();

    // Wait for network activities to finish
    await page.waitForTimeout(8395);

    const responsePromise2 = page.waitForResponse("**/api/v1/user/me/**");
    await page.getByRole("button", { exact: true, name: "Remove from favorites" }).click();
    const response2 = await responsePromise2;
    expect(response2.status()).toBe(200);
    await expect(page.getByRole("button", { exact: true, name: "Add to favorites" })).toBeVisible();
    await expect(page.getByText("Project removed from favorites")).toBeVisible();

    expect(errors).toHaveLength(0);
});
