// Generated by Skyramp v1.3.27 on 2026-06-21 17:33:43.164878522 +0000 UTC m=+1463.026030787
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_dashboard_dropzone_upload.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/e2e/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_dashboard_upload_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(274000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);
    await page.goto("http://localhost:8080/organizations/158e6fe7-4e4b-4b91-aa16-4f2b26afab3e/projects/secret-management/ed56eff3-e303-49be-a2d8-0b340f789f35/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-upload-state]').waitFor({ state: 'visible', timeout: 20000 });
    await page.waitForSelector("text=Drag and drop a .env");
    await expect(page.getByRole("heading", { name: "Secrets Management" })).toBeVisible();
    await expect(page.getByRole("tab", { name: "Development" })).toBeVisible();
    // File upload
    const fileChooserPromise0 = page.waitForEvent("filechooser");
    await page.locator("#fileSelect").click();
    const fileChooser0 = await fileChooserPromise0;
    await fileChooser0.setFiles({
        name: 'test.env',
        mimeType: 'text/plain',
        buffer: Buffer.from('API_KEY=test-key-123\nDB_HOST=localhost\nDB_PORT=5432\n')
    });
    // Wait for additional time after file upload
    await page.waitForTimeout(1500);

    await expect(page.getByText("pending changes")).toContainText("3 pending changes");
    await expect(page.getByRole("button", { name: "Save Changes" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
