// Generated by Skyramp v1.3.27 on 2026-06-21 17:25:47.320093169 +0000 UTC m=+987.181245428
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_dropzone_upload_lifecycle.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/e2e/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_dropzone_upload_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1509000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error) => errors.push(error));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(12000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.locator("#new-project-name").fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.waitForSelector("text=Upload your secrets");
    await page.getByRole("combobox").click();
    await page.getByRole("option", { name: "Development" }).click();
    await page.keyboard.press("Escape");
    await page.locator("#fileSelect").setInputFiles({
        name: 'test.env',
        mimeType: 'text/plain',
        buffer: Buffer.from('API_KEY=test-key-123\nDB_HOST=localhost\nDB_PORT=5432\n')
    });
    await page.waitForTimeout(2000);
    await expect(page.getByText("pending changes")).toContainText("3 pending changes");
    await expect(page.getByRole("button", { name: "Save Changes" })).toBeVisible();
    expect(errors).toHaveLength(0);
});
