// Generated by Skyramp v1.3.37 on 2026-08-09 22:42:42.971182061 +0000 UTC m=+552.093386358
// Command: skyramp generate contract rest http://host.docker.internal:8080/api/v2/folders \
// 		--api-schema http://localhost:8080/api/docs/json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output folder_listing_missing_params_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 400 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://host.docker.internal:8080");

// contract test for /api/v2/folders GET
test('testFoldersGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedFoldersGetResponseBody: string = `{
        "error": "Bad Request",
        "message": "querystring must have required property 'projectId'",
        "reqId": "req-abc123def",
        "statusCode": 400
    }`;

    // Execute Request
    const foldersGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v2/folders",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": null,
            "lastSecretModified": null,
            "path": null,
            "projectId": null,
            "recursive": "false"
        }
    });

    // Generated Assertions
    expect(foldersGetResponse.statusCode, 'status code').toBe(400);
    expect(checkSchema(foldersGetResponse, expectedFoldersGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(foldersGetResponse, "error"), 'value').not.toBeNull();
    expect(getResponseValue(foldersGetResponse, "message"), 'value').not.toBeNull();
    expect(getResponseValue(foldersGetResponse, "reqId"), 'value').not.toBeNull();
    expect(getResponseValue(foldersGetResponse, "error")).toBe("Bad Request");
    expect(getResponseValue(foldersGetResponse, "statusCode")).toBe(400);
});
