// Generated by Skyramp v1.3.37 on 2026-08-09 22:42:56.177832258 +0000 UTC m=+565.300036565
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output folder_listing_business_rule_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_folder-listing-business-rule.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_host = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://host.docker.internal:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const workspacePostRequestBody: string = `{
        "projectName": "skyramp-folder-biz-rule"
    }`;

    // Execute Request
    const workspacePostResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/workspace",
        method: "POST",
        body: workspacePostRequestBody,
        headers: headers,
        dataOverride: {"projectName": uniqueSuffix("skyramp-folder-biz-rule")}
    });

    // Generated Assertions
    expect(workspacePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(workspacePostResponse, 'project.id')).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(workspacePostResponse, 'project.slug')).not.toBeNull();

    // Request Body
    const foldersPostRequestBody: string = `{
        "environment": "dev",
        "name": "test-folder",
        "path": "/",
        "projectId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
    }`;

    // Execute Request
    const foldersPostResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/folders",
        method: "POST",
        body: foldersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(foldersPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersPostResponse, 'folder.name')).toBe('test-folder');
    expect(getResponseValue(foldersPostResponse, 'folder.id')).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Execute Request
    const foldersGetResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/folders",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "path": ["/"],
            "projectId": ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]
        }
    });

    // Generated Assertions
    expect(foldersGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersGetResponse, 'folders').length).toBeGreaterThanOrEqual(1);
    expect(getResponseValue(foldersGetResponse, 'folders.0.id')).toBe(getResponseValue(foldersPostResponse, 'folder.id'));
    expect(getResponseValue(foldersGetResponse, 'folders.0.name')).toBe('test-folder');

    // Request Body
    const foldersFoldersDeleteRequestBody: string = `{
        "environment": "dev",
        "path": "/",
        "projectId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
    }`;

    // Execute Request
    const foldersFoldersDeleteResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/folders/{folders}",
        method: "DELETE",
        body: foldersFoldersDeleteRequestBody,
        headers: headers,
        pathParams: {"folders": getResponseValue(foldersPostResponse, "folder.id")}
    });

    // Generated Assertions
    expect(foldersFoldersDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersFoldersDeleteResponse, 'folder.id')).toBe(getResponseValue(foldersPostResponse, 'folder.id'));
    expect(getResponseValue(foldersFoldersDeleteResponse, 'folder.name')).toBe('test-folder');

    // Execute Request
    const workspaceWorkspaceDeleteResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/workspace/{workspace}",
        method: "DELETE",
        headers: headers,
        pathParams: {"workspace": getResponseValue(workspacePostResponse, "project.slug")}
    });

    // Generated Assertions
    expect(workspaceWorkspaceDeleteResponse.statusCode, 'status code').toBe(204);
});
