// Generated by Skyramp v1.3.37 on 2026-08-09 22:42:58.442870841 +0000 UTC m=+567.565075138
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output folder_lifecycle_create_list_delete_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_folder-lifecycle-create-list-delete.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_host = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://host.docker.internal:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const workspacePostRequestBody: string = `{
        "projectName": "skyramp-lifecycle-test"
    }`;

    // Execute Request
    const workspacePostResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/workspace",
        method: "POST",
        body: workspacePostRequestBody,
        headers: headers,
        dataOverride: {"projectName": uniqueSuffix("skyramp-lifecycle-test")}
    });

    // Generated Assertions
    expect(workspacePostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(workspacePostResponse, 'project.id')).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(workspacePostResponse, 'project.slug')).not.toBeNull();

    // Request Body
    const foldersPostRequestBody: string = `{
        "environment": "dev",
        "name": "lifecycle-folder",
        "path": "/",
        "projectId": "c3d4e5f6-a7b8-9012-cdef-123456789012"
    }`;

    // Execute Request
    const foldersPostResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/folders",
        method: "POST",
        body: foldersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(foldersPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersPostResponse, 'folder.name')).toBe('lifecycle-folder');
    expect(getResponseValue(foldersPostResponse, 'folder.id')).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Execute Request
    const foldersGetResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/folders",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": ["dev"],
            "path": ["/"],
            "projectId": ["c3d4e5f6-a7b8-9012-cdef-123456789012"]
        }
    });

    // Generated Assertions
    expect(foldersGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(foldersGetResponse, 'folders').length).toBeGreaterThanOrEqual(1);
    expect(getResponseValue(foldersGetResponse, 'folders.0.id')).toBe(getResponseValue(foldersPostResponse, 'folder.id'));
    expect(getResponseValue(foldersGetResponse, 'folders.0.name')).toBe('lifecycle-folder');

    // Execute Request
    const workspaceWorkspaceDeleteResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/workspace/{workspace}",
        method: "DELETE",
        headers: headers,
        pathParams: {"workspace": getResponseValue(workspacePostResponse, "project.slug")}
    });

    // Generated Assertions
    expect(workspaceWorkspaceDeleteResponse.statusCode, 'status code').toBe(204);
});
