// Generated by Skyramp v1.3.37 on 2026-08-09 22:51:52.759680037 +0000 UTC m=+817.190390468
// Command: skyramp generate contract rest http://host.docker.internal:8080/api/v1/workspace/3fa85f64-5717-4562-b3fc-2c963f66afa6/tags \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output secret_tag_create_without_auth_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--request-data {"slug":"no-auth-tag","color":"#FFFFFF"} \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://host.docker.internal:8080");

// contract test for /api/v1/workspace/3fa85f64-5717-4562-b3fc-2c963f66afa6/tags POST
test('testTagsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const tagsPostRequestBody: string = `{
        "color": "#FFFFFF",
        "slug": "no-auth-tag"
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/workspace/3fa85f64-5717-4562-b3fc-2c963f66afa6/tags",
        method: "POST",
        body: tagsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(401);
    expect(getValue(tagsPostResponse, "statusCode")).toBe(401);
    expect(getValue(tagsPostResponse, "error")).toBe("UnauthorizedError");
    expect(getValue(tagsPostResponse, "message")).toBe("Token missing");
});
