// Generated by Skyramp v1.3.37 on 2026-08-09 22:52:33.197743216 +0000 UTC m=+857.628453657
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_tag_update_cache_invalidation_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret-tag-update-cache-invalidation.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_host = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://host.docker.internal:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const v2WorkspacePostRequestBody: string = `{
        "projectName": "tag-cache-test"
    }`;

    // Execute Request
    const v2WorkspacePostResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/workspace",
        method: "POST",
        body: v2WorkspacePostRequestBody,
        headers: headers,
        dataOverride: {"projectName": uniqueSuffix("tag-cache-test")}
    });

    // Generated Assertions
    expect(v2WorkspacePostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(v2WorkspacePostResponse, "project.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(v2WorkspacePostResponse, "project.createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Request Body
    const tagsPostRequestBody: string = `{
        "color": "#FF0000",
        "slug": "original-slug"
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/workspace/{workspace}/tags",
        method: "POST",
        body: tagsPostRequestBody,
        headers: headers,
        pathParams: {"workspace": getResponseValue(v2WorkspacePostResponse, "project.id")},
        dataOverride: {"slug": uniqueSuffix("original-slug")}
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(tagsPostResponse, "workspaceTag.color")).toBe("#FF0000");
    expect(getResponseValue(tagsPostResponse, "workspaceTag.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(tagsPostResponse, "workspaceTag.createdAt")).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(tagsPostResponse, "workspaceTag.projectId")).toBe(getResponseValue(v2WorkspacePostResponse, "project.id"));

    // Execute Request
    const tagsGetResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/workspace/{workspace}/tags",
        method: "GET",
        headers: headers,
        pathParams: {"workspace": getResponseValue(v2WorkspacePostResponse, "project.id")}
    });

    // Generated Assertions
    expect(tagsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsGetResponse, "workspaceTags").length).toBe(1);
    expect(getResponseValue(tagsGetResponse, "workspaceTags.0.id")).toBe(getResponseValue(tagsPostResponse, "workspaceTag.id"));
    expect(getResponseValue(tagsGetResponse, "workspaceTags.0.slug")).toBe(getResponseValue(tagsPostResponse, "workspaceTag.slug"));
    expect(getResponseValue(tagsGetResponse, "workspaceTags.0.color")).toBe("#FF0000");
    expect(getResponseValue(tagsGetResponse, "workspaceTags.1")).toBeUndefined();

    // Request Body
    const tagsTagsPatchRequestBody: string = `{
        "color": "#00FF00",
        "slug": "updated-slug"
    }`;

    // Execute Request
    const tagsTagsPatchResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/workspace/{workspace}/tags/{tags}",
        method: "PATCH",
        body: tagsTagsPatchRequestBody,
        headers: headers,
        pathParams: {
            "tags": getResponseValue(tagsPostResponse, "workspaceTag.id"),
            "workspace": getResponseValue(v2WorkspacePostResponse, "project.id")
        }
    });

    // Generated Assertions
    expect(tagsTagsPatchResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(tagsTagsPatchResponse, "workspaceTag.id")).toBe(getResponseValue(tagsPostResponse, "workspaceTag.id"));
    expect(getResponseValue(tagsTagsPatchResponse, "workspaceTag.slug")).toBe("updated-slug");
    expect(getResponseValue(tagsTagsPatchResponse, "workspaceTag.color")).toBe("#00FF00");

    // Execute Request
    const tagsGet1Response = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/workspace/{workspace}/tags",
        method: "GET",
        headers: headers,
        pathParams: {"workspace": getResponseValue(v2WorkspacePostResponse, "project.id")}
    });

    // Generated Assertions
    expect(tagsGet1Response.statusCode, 'status code').toBe(200);
    expect(getValue(tagsGet1Response, "workspaceTags").length).toBe(1);
    expect(getResponseValue(tagsGet1Response, "workspaceTags.0.id")).toBe(getResponseValue(tagsPostResponse, "workspaceTag.id"));
    expect(getResponseValue(tagsGet1Response, "workspaceTags.0.slug")).toBe("updated-slug");
    expect(getResponseValue(tagsGet1Response, "workspaceTags.0.color")).toBe("#00FF00");
    expect(getResponseValue(tagsGet1Response, "workspaceTags.1")).toBeUndefined();

    // Execute Request
    const tagsTagsDeleteResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/workspace/{workspace}/tags/{tags}",
        method: "DELETE",
        headers: headers,
        pathParams: {
            "tags": getResponseValue(tagsPostResponse, "workspaceTag.id"),
            "workspace": getResponseValue(v2WorkspacePostResponse, "project.id")
        }
    });

    // Generated Assertions
    expect(tagsTagsDeleteResponse.statusCode, 'status code').toBe(204);

    // Execute Request
    const workspaceDeleteResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/workspace/{workspace}",
        method: "DELETE",
        headers: headers,
        pathParams: {"workspace": getResponseValue(v2WorkspacePostResponse, "project.id")}
    });

    // Generated Assertions
    expect(workspaceDeleteResponse.statusCode, 'status code').toBe(204);
});
