// Generated by Skyramp v1.3.34 on 2026-08-09 03:39:10.963548102 +0000 UTC m=+223.701853562
// Command: skyramp generate contract rest http://host.docker.internal:8080/api/status \
// 		--api-schema http://localhost:8080/api/docs/json \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output status_apiversion_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://host.docker.internal:8080");

// contract test for /api/status GET
test('testStatusGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedStatusGetResponseBody: string = `{
        "apiVersion": "v1",
        "date": "2026-08-09T03:39:10Z"
    }`;

    // Execute Request
    const statusGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/status",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(statusGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(statusGetResponse, expectedStatusGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(statusGetResponse, "apiVersion"), 'apiVersion').toBe("v1");
    expect(getResponseValue(statusGetResponse, "message"), 'message').toBe("Ok");
    expect(getResponseValue(statusGetResponse, "date"), 'date format').toMatch(/^\d{4}-\d{2}-\d{2}T/);
});
