// Generated by Skyramp v1.3.37 on 2026-08-10 01:10:50.863789498 +0000 UTC m=+542.578765330
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output webhooks_list_with_signing_key_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_webhooks-list-with-signing-key.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';

// URL for test requests
const URL_host = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://host.docker.internal:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const workspacePostRequestBody: string = `{
        "projectName": "webhook-sig-enabled-test"
    }`;

    // Execute Request
    const workspacePostResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/workspace",
        method: "POST",
        body: workspacePostRequestBody,
        headers: headers,
        dataOverride: {"projectName": uniqueSuffix("webhook-sig-enabled-test")}
    });

    // Generated Assertions
    expect(workspacePostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(workspacePostResponse, "workspace.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Request Body
    const webhooksPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "webhookSecretKey": "test-signing-secret-key",
        "webhookUrl": "https://example.com/webhook"
    }`;

    // Execute Request
    const webhooksPostResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/webhooks",
        method: "POST",
        body: webhooksPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(webhooksPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(webhooksPostResponse, "webhook.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Execute Request
    const webhooksGetResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/webhooks",
        method: "GET",
        headers: headers,
        queryParams: {"projectId": ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]}
    });

    // Generated Assertions
    expect(webhooksGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(webhooksGetResponse, "message")).toBe("Successfully fetched webhook");
    expect(getResponseValue(webhooksGetResponse, "webhooks").length).toBeGreaterThanOrEqual(1);
    expect(getResponseValue(webhooksGetResponse, "webhooks.0.id")).toBe(getResponseValue(webhooksPostResponse, "webhook.id"));
    expect(getResponseValue(webhooksGetResponse, "webhooks.0.signature.enabled")).toBe(true);
    expect(getResponseValue(webhooksGetResponse, "webhooks.0.signature.key")).toBe("test-signing-secret-key");

    // Execute Request
    const webhooksWebhooksDeleteResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v1/webhooks/{webhooks}",
        method: "DELETE",
        headers: headers,
        pathParams: {"webhooks": getResponseValue(webhooksPostResponse, "webhook.id")}
    });

    // Generated Assertions
    expect(webhooksWebhooksDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(webhooksWebhooksDeleteResponse, "webhook.id")).toBe(getResponseValue(webhooksPostResponse, "webhook.id"));

    // Execute Request
    const workspaceWorkspaceDeleteResponse = await client.sendRequest({
        url: URL_host,
        path: "/api/v2/workspace/{workspace}",
        method: "DELETE",
        headers: headers,
        pathParams: {"workspace": getResponseValue(workspacePostResponse, "workspace.name")}
    });

    // Generated Assertions
    expect(workspaceWorkspaceDeleteResponse.statusCode, 'status code').toBe(204);
});
