// Generated by Skyramp v1.3.37 on 2026-08-10 01:10:57.710321454 +0000 UTC m=+549.425297276
// Command: skyramp generate contract rest http://host.docker.internal:8080/api/v1/webhooks \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output webhooks_create_invalid_url_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--request-data {"projectId":"00000000-0000-0000-0000-000000000001","environment":"dev","webhookUrl":"not-a-valid-url"} \
// 		--response-status-code 400 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://host.docker.internal:8080");

// contract test for /api/v1/webhooks POST
test('testWebhooksPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const webhooksPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "00000000-0000-0000-0000-000000000001",
        "webhookUrl": "not-a-valid-url"
    }`;

    // Execute Request
    const webhooksPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/webhooks",
        method: "POST",
        body: webhooksPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(webhooksPostResponse.statusCode, 'status code').toBe(400);
    expect(getValue(webhooksPostResponse, "error")).toBe("Bad Request");
    expect(getValue(webhooksPostResponse, "message")).not.toBeNull();
});
