// Generated by Skyramp v1.3.33 on 2026-07-12 08:41:13.134262197 +0000 UTC m=+256.915223682
// Command: skyramp generate contract rest http://localhost:8080/api/status \
// 		--api-schema http://localhost:8080/api/docs/json \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output status_apiversion_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/backend/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--response-data {"date":"2026-07-12T08:39:44.287Z","message":"Ok","apiVersion":"v1","emailConfigured":false,"inviteOnlySignup":true,"redisConfigured":true,"secretScanningConfigured":false,"auditLogStorageDisabled":false,"maxIdentityAccessTokenTTL":7776000} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/status GET
test('testStatusGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedStatusGetResponseBody: string = `{
        "apiVersion": "v1",
        "auditLogStorageDisabled": false,
        "date": "2026-07-12T08:39:44.287Z",
        "emailConfigured": false,
        "inviteOnlySignup": true,
        "maxIdentityAccessTokenTTL": 7776000,
        "message": "Ok",
        "redisConfigured": true,
        "secretScanningConfigured": false
    }`;

    // Execute Request
    const statusGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/status",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(statusGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(statusGetResponse, expectedStatusGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(statusGetResponse, "apiVersion"), 'apiVersion').toBe("v1");
    expect(getResponseValue(statusGetResponse, "message"), 'message').toBe("Ok");
    expect(getResponseValue(statusGetResponse, "emailConfigured"), 'emailConfigured').toBe(false);
    expect(getResponseValue(statusGetResponse, "inviteOnlySignup"), 'inviteOnlySignup').toBe(true);
    expect(getResponseValue(statusGetResponse, "redisConfigured"), 'redisConfigured').toBe(true);
    expect(getResponseValue(statusGetResponse, "secretScanningConfigured"), 'secretScanningConfigured').toBe(false);
    expect(getResponseValue(statusGetResponse, "auditLogStorageDisabled"), 'auditLogStorageDisabled').toBe(false);
    expect(getResponseValue(statusGetResponse, "maxIdentityAccessTokenTTL"), 'maxIdentityAccessTokenTTL').toBe(7776000);
    expect(getResponseValue(statusGetResponse, "date"), 'date').toMatch(/^\d{4}-\d{2}-\d{2}T/);
});
