// Generated by Skyramp v1.3.33 on 2026-07-12 05:27:39.013596256 +0000 UTC m=+833.506813448
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output create_secret_form_valid_name_submit_success.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/create_secret_form_valid_name_submit_success_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(224000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    const existingProject = page.getByRole("link", { name: "Testbot Project" });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        const addNewProjectBtn = page.getByRole("button", { name: "Add New Project" });
        if (await addNewProjectBtn.isVisible().catch(() => false)) {
            await addNewProjectBtn.click();
        } else {
            await page.getByRole("button", { name: "Create Project" }).click();
        }
        await page.locator("#new-project-name").fill("Testbot Project");
        await page.getByRole("button", { name: "Create Project" }).click();
    }
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const secretKey = `TESTBOT_SECRET_KEY_${Date.now()}`;
    await page.waitForSelector("text=Add Secret");
    await page.getByText("Add Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill(secretKey);
    await page.getByRole("textbox", { name: "secret value" }).fill("testbot-secret-value-456");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue(secretKey);
    await expect(page.getByRole("row", { name: new RegExp(secretKey) })).toHaveCount(1);

    expect(pageErrors).toHaveLength(0);
});
