// Generated by Skyramp v1.3.37 on 2026-08-09 19:10:14.918686375 +0000 UTC m=+962.688577337
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output data_grid_total_count_secrets_dashboard.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/data_grid_total_count_secrets_dashboard_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1099000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/projects/search**");
    await page.locator("main").getByRole("tab", { name: "All Projects" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.locator("main").getByRole("row", { name: "BaselineProject" }).first().click();
    const url0 = `http://localhost:8080/organizations/${getValue(await response1.text(), "projects.0.orgId")}/projects/secret-management/${getValue(await response1.text(), "projects.0.id")}/secrets/dev`;
    await page.goto(url0);
    await page.waitForLoadState('networkidle');

    await page.waitForSelector("text=Retrieving your encrypted secrets...", { state: "hidden" });
    await expect(page.getByRole("heading", { name: "Secrets Management" })).toBeVisible();
    await expect(page.getByRole("tab", { name: "Development" })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
