// Generated by Skyramp v1.3.37 on 2026-08-09 19:10:13.005943666 +0000 UTC m=+960.775834638
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output data_grid_total_count_environment_tab_switch.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/data_grid_total_count_environment_tab_switch_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(180000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/2708a6e7-2cf7-4b2d-b461-82dd6f8d5380/projects/secret-management/15600c77-3d99-4c8d-a0fe-96e01f48693a/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.waitForSelector("text=Development");
    await expect(page.getByRole("tab", { name: "Development" })).toBeVisible();
    await page.getByRole("tab", { name: "Staging" }).click();
    await expect(page).toHaveURL(/\/secrets\/staging/);
    await expect(page.getByRole("heading", { name: "Secrets Management" })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
