// Generated by Skyramp v1.3.27 on 2026-06-21 17:25:03.361826776 +0000 UTC m=+963.060527697
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_search_by_key.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_item_search_by_key_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(513000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/ea4a7a08-974c-43b0-accb-3227eafcee6a/projects/secret-management/b608214b-8ae8-4a11-b67d-fae4336d4fb5/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="secret-row"]').waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("combobox", { name: "Search by secret, folder, tag" }).fill("TEST_API_KEY");
    await expect(page).toHaveURL(/search=TEST_API_KEY/);
    await expect(page.getByRole("combobox", { name: "Search by secret, folder, tag" })).toHaveValue("TEST_API_KEY");
    await expect(page.getByText("- 1 of 1")).toContainText("1 - 1 of 1");
    await expect(page.locator('[data-testid="secret-row"]')).toHaveCount(1);
    await expect(page.locator('[data-testid="secret-row"]')).toHaveAttribute('data-secret-key', 'TEST_API_KEY');

    expect(pageErrors).toHaveLength(0);
});
