// Generated by Skyramp v1.3.37 on 2026-08-09 19:11:29.84700626 +0000 UTC m=+896.329448521
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_url_deep_link_page_restore_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_url_deep_link_page_restore_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(183000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/organizations/51964d54-c8da-4295-af2c-27e13fa3ba72/projects/secret-management/302a60bd-81a2-470a-a27f-0279bda02c56/overview?orderDirection=DESC");
    // Wait for network activities to finish
    await page.waitForTimeout(2250);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:8080/organizations/51964d54-c8da-4295-af2c-27e13fa3ba72/projects/secret-management/302a60bd-81a2-470a-a27f-0279bda02c56/overview?orderDirection=DESC");
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(/orderDirection=DESC/);
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("MY_SECRET");

    expect(pageErrors).toHaveLength(0);
});
