// Generated by Skyramp v1.3.27 on 2026-06-22 21:53:00.630498871 +0000 UTC m=+1309.333002668
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_search_filter_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_item_search_filter_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(163000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/4ae7f925-93f9-4e5b-a166-b6e7e8e44ac3/projects/secret-management/9694e8d4-9177-455a-8ef8-a851968256cd/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="secret-row"]').first().waitFor({ state: 'visible', timeout: 15000 });
    await expect(page.locator('[data-testid="secret-row"]')).toHaveCount(2);
    await page.getByRole("combobox", { name: "Search by secret, folder, tag" }).fill("MY_TEST");
    await expect(page.locator('[data-testid="secret-row"]')).toHaveCount(1);
    await expect(page.locator('[data-testid="secret-row"]').first()).toHaveAttribute('data-secret-key', 'MY_TEST_SECRET');
    expect(pageErrors).toHaveLength(0);
});
