// Generated by Skyramp
// UI test: a secret row in the dashboard is locatable and shows its key.

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(795000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    page.setDefaultTimeout(pageTimeout);
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.waitForTimeout(7500);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.locator("#new-project-name").fill("BaselineProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.waitForTimeout(3000);

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("BASELINE_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("baseline-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await page.waitForTimeout(5000);

    const overviewUrl = page.url();
    const devSecretsUrl = overviewUrl.replace(/\/overview.*$/, '/secrets/dev');
    await page.goto(devSecretsUrl);
    await page.waitForLoadState('networkidle');

    // Locate the secret row by its row-container styling and assert it renders the key.
    const secretRow = page.locator("div.border-b.bg-mineshaft-800");
    await secretRow.first().waitFor({ state: 'visible', timeout: 15000 });
    await expect(secretRow).toHaveCount(1);
    await expect(secretRow.getByRole("textbox").first()).toHaveValue("BASELINE_KEY");

    expect(pageErrors).toHaveLength(0);
});
