// Generated by Skyramp v1.3.27 on 2026-06-21 17:18:43.972374474 +0000 UTC m=+583.671075415
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_row_attributes.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_item_row_attributes_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(795000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(7500);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Add New Project" }).click();
    await page.locator("#new-project-name").fill("TestProject");
    await page.getByRole("button", { name: "Create Project" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_API_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("secret-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    // Navigate to the dev environment secrets page (SecretDashboardPage) where data-testid="secret-row" is rendered
    const overviewUrl = page.url();
    const devSecretsUrl = overviewUrl.replace(/\/overview.*$/, '/secrets/dev');
    await page.goto(devSecretsUrl);
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="secret-row"]').waitFor({ state: 'visible', timeout: 15000 });

    await expect(page.locator('[data-testid="secret-row"]')).toHaveCount(1);
    await expect(page.locator('[data-testid="secret-row"]')).toHaveAttribute('data-secret-key', 'TEST_API_KEY');
    await expect(page.locator('[data-testid="secret-row"]').getByRole("textbox").first()).toHaveValue("TEST_API_KEY");
    await expect(page.getByText("1 - 1 of 1")).toHaveText("1 - 1 of 1");

    expect(pageErrors).toHaveLength(0);
});
