// Generated by Skyramp v1.3.27 on 2026-06-21 17:27:53.624811359 +0000 UTC m=+1133.323512290
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_multi_secret_attributes.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_item_multi_secret_attributes_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(211000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/ea4a7a08-974c-43b0-accb-3227eafcee6a/projects/secret-management/b608214b-8ae8-4a11-b67d-fae4336d4fb5/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.locator("button", { hasText: "Add Secret" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "Add Secret" }).click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("DB_PASSWORD");
    await page.getByRole("textbox", { name: "secret value" }).fill("db-secret-456");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await page.getByRole("button", { name: "Save Changes" }).click();
    await expect(page.getByText("- 2 of 2")).toContainText("1 - 2 of 2");
    await expect(page.getByRole("textbox").first()).toHaveValue("DB_PASSWORD");
    await expect(page.getByRole("textbox").nth(1)).toHaveValue("TEST_API_KEY");
    await expect(page.locator('[data-testid="secret-row"]')).toHaveCount(2);
    await expect(page.locator('[data-testid="secret-row"]').first()).toHaveAttribute('data-secret-key', 'DB_PASSWORD');
    await expect(page.locator('[data-testid="secret-row"]').nth(1)).toHaveAttribute('data-secret-key', 'TEST_API_KEY');

    expect(pageErrors).toHaveLength(0);
});
