// Generated by Skyramp v1.3.27 on 2026-06-22 21:52:59.524837224 +0000 UTC m=+1308.227341011
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_multi_key_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_item_multi_key_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(280000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/4ae7f925-93f9-4e5b-a166-b6e7e8e44ac3/projects/secret-management/9694e8d4-9177-455a-8ef8-a851968256cd/secrets/dev");
    await page.waitForLoadState('networkidle');
    await page.locator('[data-testid="secret-row"]').first().waitFor({ state: 'visible', timeout: 15000 });
    await page.getByRole("button", { name: "Add Secret" }).click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("SECOND_SECRET_KEY");
    await page.getByRole("textbox", { name: "secret value" }).fill("second_value_456");
    await page.getByRole("button", { name: "Create Secret" }).click();
    await expect(page.getByRole("textbox", { name: "Type your secret name" })).toHaveValue("SECOND_SECRET_KEY");
    await expect(page.locator('[data-testid="secret-row"]')).toHaveCount(2);
    await expect(page.locator('[data-testid="secret-row"]').nth(0)).toHaveAttribute('data-secret-key', 'SECOND_SECRET_KEY');
    await expect(page.locator('[data-testid="secret-row"]').nth(1)).toHaveAttribute('data-secret-key', 'MY_TEST_SECRET');
    await page.getByRole("button", { name: "Save Changes" }).click();
    await expect(page.locator('[data-testid="secret-row"]')).toHaveCount(2);
    expect(pageErrors).toHaveLength(0);
});
