// Generated by Skyramp v1.3.37 on 2026-08-09 19:05:14.33528841 +0000 UTC m=+687.910042989
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_import_row_staging_display_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_import_row_attributes_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(877000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("button", { name: "Secrets Management" }).click();

    const existingProject = page.getByRole('link', { name: 'TestImportProject' });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.locator("#new-project-name").fill("TestImportProject");
        await page.getByRole("button", { name: "Create Project" }).click();
    }
    await page.waitForTimeout(3000);
    const overviewUrl = page.url();
    const devUrl = overviewUrl.replace(/\/overview.*$/, '/secrets/dev');
    await page.goto(devUrl);
    await page.waitForLoadState('networkidle');

    await page.waitForSelector("text=Add Secret");

    const existingImport = page.getByRole("button", { name: "staging / expand delete" });
    if (!(await existingImport.isVisible().catch(() => false))) {
        await page.locator("main").getByRole("button", { name: "add-folder-or-import" }).click();
        await page.getByRole("button", { name: "Add Import" }).click();
        await page.locator("#react-select-2-input").click();
        await page.getByRole("option", { name: "Staging" }).click();
        await page.getByRole("button", { name: "Create Link" }).click();
        await page.waitForTimeout(5000);
        await page.waitForSelector("text=staging");
    }

    await expect(page.getByRole("button", { name: "staging / expand delete" })).toHaveCount(1);
    await expect(page.getByRole("button", { name: "staging / expand delete" })).toContainText("staging");
    await expect(page.getByRole("button", { name: "expand", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "delete", exact: true })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
