// Generated by Skyramp v1.3.37 on 2026-08-09 19:14:11.680850723 +0000 UTC m=+1096.219554268
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_row_stable_selector_multiple_secrets_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_row_stable_selector_multiple_secrets_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(192000);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();

    const existingProject = page.getByRole('link', { name: 'TestProject' });
    if (await existingProject.isVisible().catch(() => false)) {
        await existingProject.click();
    } else {
        await page.getByRole("button", { name: "Add New Project" }).click();
        await page.locator("#new-project-name").fill("TestProject");
        await page.getByRole("button", { name: "Create Project" }).click();
        await page.waitForTimeout(3000);
    }

    const overviewUrl = page.url();
    const devSecretsUrl = overviewUrl.replace(/\/overview.*$/, '/secrets/dev');
    await page.goto(devSecretsUrl);
    await page.waitForLoadState('networkidle');

    const existingFirstSecret = page.locator('[data-secret-key="MY_SECRET_KEY"]');
    if (!await existingFirstSecret.isVisible().catch(() => false)) {
        await page.getByRole("button", { name: "Add Secret" }).click();
        await page.getByRole("textbox", { name: "Type your secret name" }).fill("MY_SECRET_KEY");
        await page.getByRole("textbox", { name: "secret value" }).fill("my-secret-value");
        await page.getByRole("button", { name: "Create Secret" }).click();
        await page.waitForTimeout(1500);
        await page.getByRole("button", { name: "Save Changes" }).click();
        await page.waitForTimeout(3000);
    }

    const existingSecondSecret = page.locator('[data-secret-key="SECOND_KEY"]');
    if (!await existingSecondSecret.isVisible().catch(() => false)) {
        await page.getByRole("button", { name: "Add Secret" }).click();
        await page.getByRole("textbox", { name: "Type your secret name" }).fill("SECOND_KEY");
        await page.getByRole("textbox", { name: "secret value" }).fill("second-value-456");
        await page.getByRole("button", { name: "Create Secret" }).click();
        // Wait to finish any potential hydration
        await page.waitForTimeout(1500);
        const responsePromise1 = page.waitForResponse("**/api/v1/pit/batch/commit**");
        await page.getByRole("button", { name: "Save Changes" }).click();
        const response1 = await responsePromise1;
        expect(response1.status()).toBe(200);
    }

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const secretRow = page.locator('[data-testid="secret-row"]');
    await secretRow.first().waitFor({ state: 'visible', timeout: 15000 });
    await expect(secretRow).toHaveCount(2);
    await expect(secretRow.nth(0)).toHaveAttribute('data-secret-key', 'MY_SECRET_KEY');
    await expect(secretRow.nth(1)).toHaveAttribute('data-secret-key', 'SECOND_KEY');

    expect(pageErrors).toHaveLength(0);
});
