// Generated by Skyramp v1.3.37 on 2026-08-09 19:18:29.209451394 +0000 UTC m=+1642.404432364
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_sidebar_accordion_triggers_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_sidebar_accordion_triggers_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(300000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:8080/login");
    await page.waitForTimeout(3000);

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    await page.goto("http://localhost:8080/organizations/5a021cef-4f81-4d73-bf5f-ab5ea500638d/projects/secret-management/a2eb05d9-5d32-4085-888b-8558ce89705d/secrets/dev");
    await page.waitForTimeout(5000);
    await page.getByRole("button", { name: "more" }).click();
    await page.waitForTimeout(3000);

    await expect(page.getByRole("heading", { name: "Metadata", level: 3 })).toBeVisible();
    await expect(page.getByRole("button", { name: "Metadata" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Version History", level: 3 })).toBeVisible();
    await expect(page.getByRole("button", { name: "Version History" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Access List", level: 3 })).toBeVisible();
    await expect(page.getByRole("button", { name: "Access List" })).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
