// Generated by Skyramp v1.3.37 on 2026-08-09 19:16:51.058497802 +0000 UTC m=+1544.253478771
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_sidebar_metadata_accordion_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2100000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:8080/login");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(20000);

    await page.getByRole("button", { name: "Secrets Management" }).click();

    const existingProject = page.getByRole("link", { name: "AccordionTestProject" });
    if (await existingProject.isVisible().catch(() => false)) {
      await existingProject.click();
    } else {
      await page.getByRole("button", { name: "Add New Project" }).click();
      await page.locator("#new-project-name").fill("AccordionTestProject");
      await page.getByRole("button", { name: "Create Project" }).click();
    }
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByText("Add a New Secret").click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill("TEST_ACCORDION_SECRET");
    await page.getByRole("textbox", { name: "secret value" }).fill("test-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(12547);

    await page.getByRole("row", { name: "TEST_ACCORDION_SECRET" }).hover();
    // Wait for network activities to finish
    await page.waitForTimeout(120000);

    await page.mouse.move(550, 411);
    await page.evaluate(() => {
  // Find buttons with aria-label containing "explore" or "detail" or similar
  const buttons = document.querySelectorAll('button');
  const labels = [];
  buttons.forEach(b => {
    const label = b.getAttribute('aria-label') || b.title || b.textContent?.trim().substring(0, 20);
    if (label) labels.push(label);
  });
  return labels.filter(l => l.length > 0 && l.length < 50);
});
    await page.locator("button:nth-child(9)").click();
    await page.keyboard.press("Escape");
    await page.mouse.move(550, 411);
    // Wait for network activities to finish
    await page.waitForTimeout(1500);

    await page.locator("body").click({ position: {"x": 930, "y": 411} });
    await page.mouse.move(550, 411);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("body").click({ position: {"x": 1128, "y": 411} });
    // Wait for network activities to finish
    await page.waitForTimeout(120000);

    await page.evaluate(() => {
  // Find the button with aria-label="more" inside the secret row
  const buttons = Array.from(document.querySelectorAll('[aria-label="more"]'));
  return buttons.map(b => ({
    ariaLabel: b.getAttribute('aria-label'),
    text: b.textContent?.trim()?.substring(0, 30),
    visible: b.getBoundingClientRect().width > 0,
    rect: b.getBoundingClientRect()
  }));
});
    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.cursor-pointer.whitespace-nowrap.text-sm.font-medium.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.text-foreground.hover\\\\:bg-foreground\\\\/10.border-transparent.data-\\\\[state\\\\=open\\\\]\\\\:bg-foreground\\\\/10.h-7.\\\\[\\\\&\\\\>svg\\\\]\\\\:size-4.rounded-sm.\\\\[\\\\&\\\\>svg\\\\]\\\\:stroke-\\\\[1\\\\.75\\\\].w-0").nth(0).click();
    // Wait for network activities to finish
    await page.waitForTimeout(60860);

    await page.getByRole("button", { name: "Metadata" }).click();

    await expect(page.getByRole("button", { name: "Metadata" })).toHaveAttribute("data-state", "open");
    await expect(page.getByRole("button", { name: "Add Key" })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
