// Generated by Skyramp v1.3.27 on 2026-06-23 00:24:35.385458828 +0000 UTC m=+1009.186699422
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_item_staged_row_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_item_staged_row_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(365000);

    const pageErrors: string[] = [];
    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:8080/login");
    await page.locator("#email").fill("admin@test.com");
    await page.locator("#current-password").fill("Password123!");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    await page.goto("http://localhost:8080/organizations/5c27bb8a-45d7-4146-9866-e7ecb7f9d0c4/projects/secret-management/e54def96-8b50-4fc1-851f-95d9ac4b160b/overview");
    await page.waitForLoadState('networkidle');
    await page.locator('[role="textbox"][aria-label="Secret name"]').waitFor({ state: 'visible', timeout: 15000 });
    await page.waitForSelector("text=Batch Edit Mode");
    await page.getByText("Batch Edit Mode", { exact: true }).click();
    await page.getByText("Add Secret").click();
    await page.getByRole("button", { name: "Close" }).click();
    await page.locator(".inline-flex.items-center.active\\\\:scale-\\\\[0\\\\.99\\\\].justify-center.border.cursor-pointer.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-all.disabled\\\\:pointer-events-none.disabled\\\\:opacity-50.\\\\[\\\\&_svg\\\\]\\\\:pointer-events-none.shrink-0.\\\\[\\\\&\\\\>svg\\\\]\\\\:shrink-0.focus-visible\\\\:ring-ring.outline-0.focus-visible\\\\:ring-2.border-project\\\\/25").click();
    await page.keyboard.press("Escape");
    await page.getByRole("textbox", { name: "Secret name" }).fill("API_KEY_TEST_UPDATED");
    await expect(page.getByText("pending change")).toHaveText("1 pending change");
    await expect(page.getByRole("textbox", { name: "Secret name" })).toHaveValue("API_KEY_TEST_UPDATED");
    expect(pageErrors).toHaveLength(0);
});
